<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>12&nbsp; 회귀 분석을 위한 추론 – ModernDive: Statistical Inference via Data Science</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./11-tell-your-story-with-data.html" rel="next">
<link href="./09-hypothesis-testing.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-803ae4f7a8810f475153517dc3c4ebae.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./10-inference-for-regression.html"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">회귀 분석을 위한 추론</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">ModernDive: Statistical Inference via Data Science</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title"><code>r ifelse(knitr::is_latex_output(), 'Statistical Inference via Data Science:  A ModernDive into R and the Tidyverse', 'Statistical Inference via Data Science')</code></span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00-foreword.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">00-foreword.html</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00-preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">머리말</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-getting-started.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">R 데이터 시작하기</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">데이터 시각화</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-wrangling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">데이터 전처리</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-tidy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">데이터 불러오기와 “깔끔한” 데이터</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">기초 회귀 분석</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-multiple-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">다중 회귀 분석</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-sampling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">표본 추출</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-confidence-intervals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Bootstrapping and Confidence Intervals</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-hypothesis-testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">가설 검정</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-inference-for-regression.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">회귀 분석을 위한 추론</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-tell-your-story-with-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">(PART) 결론</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./91-appendixA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">통계적 배경</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./92-appendixB.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">추론 예제</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./93-appendixC.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">팁과 요령</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./94-appendixD.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Learning Check Solutions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./95-appendixE.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">사용된 R 패키지 버전</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./99-references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">참고 문헌</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./NEWS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">ModernDive 1.1.0.9000</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#inf-packages" id="toc-inf-packages" class="nav-link active" data-scroll-target="#inf-packages">필요한 패키지</a></li>
  <li><a href="#회귀-분석-복습" id="toc-회귀-분석-복습" class="nav-link" data-scroll-target="#회귀-분석-복습"><span class="header-section-number">12.1</span> 회귀 분석 복습</a>
  <ul class="collapse">
  <li><a href="#강의-평가-분석" id="toc-강의-평가-분석" class="nav-link" data-scroll-target="#강의-평가-분석"><span class="header-section-number">12.1.1</span> 강의 평가 분석</a></li>
  <li><a href="#표집-시나리오" id="toc-표집-시나리오" class="nav-link" data-scroll-target="#표집-시나리오"><span class="header-section-number">12.1.2</span> 표집 시나리오</a></li>
  </ul></li>
  <li><a href="#regression-interp" id="toc-regression-interp" class="nav-link" data-scroll-target="#regression-interp"><span class="header-section-number">12.2</span> 회귀 표 해석하기</a>
  <ul class="collapse">
  <li><a href="#regression-se" id="toc-regression-se" class="nav-link" data-scroll-target="#regression-se"><span class="header-section-number">12.2.1</span> 표준 오차</a></li>
  <li><a href="#regression-test-statistic" id="toc-regression-test-statistic" class="nav-link" data-scroll-target="#regression-test-statistic"><span class="header-section-number">12.2.2</span> 검정 통계량</a></li>
  <li><a href="#p-값" id="toc-p-값" class="nav-link" data-scroll-target="#p-값"><span class="header-section-number">12.2.3</span> p-값</a></li>
  <li><a href="#신뢰-구간" id="toc-신뢰-구간" class="nav-link" data-scroll-target="#신뢰-구간"><span class="header-section-number">12.2.4</span> 신뢰 구간</a></li>
  <li><a href="#regression-table-computation" id="toc-regression-table-computation" class="nav-link" data-scroll-target="#regression-table-computation"><span class="header-section-number">12.2.5</span> R은 이 표를 어떻게 계산할까요?</a></li>
  </ul></li>
  <li><a href="#regression-conditions" id="toc-regression-conditions" class="nav-link" data-scroll-target="#regression-conditions"><span class="header-section-number">12.3</span> 회귀 추론을 위한 조건</a>
  <ul class="collapse">
  <li><a href="#잔차-복습" id="toc-잔차-복습" class="nav-link" data-scroll-target="#잔차-복습"><span class="header-section-number">12.3.1</span> 잔차 복습</a></li>
  <li><a href="#관계의-선형성" id="toc-관계의-선형성" class="nav-link" data-scroll-target="#관계의-선형성"><span class="header-section-number">12.3.2</span> 관계의 선형성</a></li>
  <li><a href="#잔차의-독립성" id="toc-잔차의-독립성" class="nav-link" data-scroll-target="#잔차의-독립성"><span class="header-section-number">12.3.3</span> 잔차의 독립성</a></li>
  <li><a href="#잔차의-정규성" id="toc-잔차의-정규성" class="nav-link" data-scroll-target="#잔차의-정규성"><span class="header-section-number">12.3.4</span> 잔차의 정규성</a></li>
  <li><a href="#등분산성" id="toc-등분산성" class="nav-link" data-scroll-target="#등분산성"><span class="header-section-number">12.3.5</span> 등분산성</a></li>
  <li><a href="#what-is-the-conclusion" id="toc-what-is-the-conclusion" class="nav-link" data-scroll-target="#what-is-the-conclusion"><span class="header-section-number">12.3.6</span> 결론이 무엇인가요?</a></li>
  </ul></li>
  <li><a href="#infer-regression" id="toc-infer-regression" class="nav-link" data-scroll-target="#infer-regression"><span class="header-section-number">12.4</span> 시뮬레이션 기반 회귀 분석 추론</a>
  <ul class="collapse">
  <li><a href="#기울기에-대한-신뢰-구간" id="toc-기울기에-대한-신뢰-구간" class="nav-link" data-scroll-target="#기울기에-대한-신뢰-구간"><span class="header-section-number">12.4.1</span> 기울기에 대한 신뢰 구간</a></li>
  <li><a href="#기울기에-대한-가설-검정" id="toc-기울기에-대한-가설-검정" class="nav-link" data-scroll-target="#기울기에-대한-가설-검정"><span class="header-section-number">12.4.2</span> 기울기에 대한 가설 검정</a></li>
  </ul></li>
  <li><a href="#inference-conclusion" id="toc-inference-conclusion" class="nav-link" data-scroll-target="#inference-conclusion"><span class="header-section-number">12.5</span> 결론</a>
  <ul class="collapse">
  <li><a href="#theory-regression" id="toc-theory-regression" class="nav-link" data-scroll-target="#theory-regression"><span class="header-section-number">12.5.1</span> 회귀에 대한 이론 기반 추론</a></li>
  <li><a href="#통계적-추론-요약" id="toc-통계적-추론-요약" class="nav-link" data-scroll-target="#통계적-추론-요약"><span class="header-section-number">12.5.2</span> 통계적 추론 요약</a></li>
  <li><a href="#추가-자료" id="toc-추가-자료" class="nav-link" data-scroll-target="#추가-자료"><span class="header-section-number">12.5.3</span> 추가 자료</a></li>
  <li><a href="#앞으로의-내용" id="toc-앞으로의-내용" class="nav-link" data-scroll-target="#앞으로의-내용"><span class="header-section-number">12.5.4</span> 앞으로의 내용</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="inference-for-regression" class="quarto-section-identifier"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">회귀 분석을 위한 추론</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>이 책의 끝에서 두 번째 장에서는 챕터 @ref(regression)와 @ref(multiple-regression)에서 처음 공부했던 회귀 모델을 다시 살펴보겠습니다. 챕터 @ref(confidence-intervals)와 @ref(hypothesis-testing)에서 배운 신뢰 구간과 가설 검정에 대한 지식을 바탕으로, 결과 변수와 설명 변수 사이의 관계를 더 깊이 이해하기 위해 통계적 추론을 적용할 수 있게 될 것입니다.</p>
<section id="inf-packages" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="inf-packages">필요한 패키지</h3>
<p>이 장에 필요한 모든 패키지를 불러오겠습니다(이미 설치되어 있다고 가정합니다). 섹션 @ref(tidyverse-package)에서 논의했듯이, <code>library(tidyverse)</code>를 실행하여 <code>tidyverse</code> 패키지를 불러오면 다음과 같이 일반적으로 사용되는 데이터 과학 패키지들을 한 번에 불러올 수 있습니다.</p>
<ul>
<li>데이터 시각화를 위한 <code>ggplot2</code></li>
<li>데이터 전처리를 위한 <code>dplyr</code></li>
<li>데이터를 “깔끔한(tidy)” 형식으로 변환하기 위한 <code>tidyr</code></li>
<li>스프레드시트 데이터를 R로 가져오기 위한 <code>readr</code></li>
<li>그뿐만 아니라 더 고급 패키지인 <code>purrr</code>, <code>tibble</code>, <code>stringr</code>, <code>forcats</code> 패키지들까지</li>
</ul>
<p>필요한 경우, R 패키지 설치 및 로드 방법에 대한 정보는 섹션 @ref(packages)를 참조하십시오.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(moderndive)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(infer)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="회귀-분석-복습" class="level2" data-number="12.1">
<h2 data-number="12.1" class="anchored" data-anchor-id="회귀-분석-복습"><span class="header-section-number">12.1</span> 회귀 분석 복습</h2>
<p>회귀 분석을 위한 추론으로 넘어가기 전에, 섹션 @ref(model1)에서 다루었던 텍사스 대학교 오스틴(University of Texas Austin)의 강의 평가 분석을 다시 떠올려 봅시다.</p>
<section id="강의-평가-분석" class="level3" data-number="12.1.1">
<h3 data-number="12.1.1" class="anchored" data-anchor-id="강의-평가-분석"><span class="header-section-number">12.1.1</span> 강의 평가 분석</h3>
<p>단순 선형 회귀 를 사용하여 우리는 다음 두 변수 사이의 관계를 모델링했습니다.</p>
<ol type="1">
<li>수치형 결과 변수 <span class="math inline">\(y\)</span> (강사의 강의 점수)</li>
<li>단일 수치형 설명 변수 <span class="math inline">\(x\)</span> (강사의 “외모” 점수)</li>
</ol>
<p>우리는 먼저 <code>moderndive</code> 패키지에 포함된 <code>evals</code> 데이터 프레임에서 변수들의 하위 집합을 선택하여 <code>evals_ch5</code> 데이터 프레임을 만들었습니다. 이 <code>evals_ch5</code> 데이터 프레임에는 분석에 필요한 변수들, 특히 강사의 강의 점수(<code>score</code>)와 외모 평점(<code>bty_avg</code>)만 포함되어 있습니다.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>evals_ch5 <span class="ot">&lt;-</span> evals <span class="sc">%&gt;%</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(ID, score, bty_avg, age)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(evals_ch5)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 463
Columns: 4
$ ID      &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,…
$ score   &lt;dbl&gt; 4.7, 4.1, 3.9, 4.8, 4.6, 4.3, 2.8, 4.1, 3.4, 4.5, 3.8, 4.5, 4.…
$ bty_avg &lt;dbl&gt; 5.00, 5.00, 5.00, 5.00, 3.00, 3.00, 3.00, 3.33, 3.33, 3.17, 3.…
$ age     &lt;int&gt; 36, 36, 36, 36, 59, 59, 59, 51, 51, 40, 40, 40, 40, 40, 40, 40…</code></pre>
</div>
</div>
<p>하위 섹션 @ref(model1EDA)에서 우리는 <code>score</code>와 <code>bty_avg</code> 사이의 관계에 대한 탐색적 데이터 분석을 수행했습니다. 그곳에서 우리는 두 변수 사이에 0.187의 약한 양의 상관관계가 존재함을 확인했습니다.</p>
<p>이는 <code>score</code>와 <code>bty_avg</code> 사이의 선형 관계를 요약하는 “최적적합(best-fitting)” 회귀선이 포함된 그림 @ref(fig:regline)의 산점도에서 입증되었습니다. 하위 섹션 @ref(leastsquares)에서 우리가 “최적적합” 선을 <em>잔차 제곱합(sum of squared residuals)</em>을 최소화하는 선으로 정의했음을 상기하십시오.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(evals_ch5, </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> bty_avg, <span class="at">y =</span> score)) <span class="sc">+</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"외모 점수"</span>, </span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"강의 점수"</span>,</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"강의 점수와 외모 점수 사이의 관계"</span>) <span class="sc">+</span>  </span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="10-inference-for-regression_files/figure-html/regline-1.png" class="img-fluid figure-img"></p>
<figcaption>회귀선이 포함된 관계.</figcaption>
</figure>
</div>
</div>
</div>
<p>이 그래프를 다시 보면서 여러분은 “그 선의 기울기가 정말 그렇게 양수인가?”라고 물을 수도 있습니다. <code>bty_avg</code> 변수가 증가함에 따라 왼쪽에서 오른쪽으로 증가하기는 하지만, 얼마나 많이 증가할까요? 이 정보를 얻기 위해 우리가 다음의 2단계 절차를 따랐음을 상기하십시오.</p>
<ol type="1">
<li>먼저 <code>lm()</code> 함수와 공식 <code>score ~ bty_avg</code>를 사용하여 선형 회귀 모델을 “적합”시켰습니다. 이 모델을 <code>score_model</code>에 저장했습니다.</li>
<li><code>moderndive</code> 패키지의 <code>get_regression_table()</code> 함수를 <code>score_model</code>에 적용하여 회귀 표를 얻었습니다.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 회귀 모델 적합:</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>score_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(score <span class="sc">~</span> bty_avg, <span class="at">data =</span> evals_ch5)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co"># 회귀 표 가져오기:</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">get_regression_table</span>(score_model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small">
<caption>이전에 보았던 선형 회귀 표</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std_error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p_value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">lower_ci</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">upper_ci</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">intercept</td>
<td style="text-align: right;">3.880</td>
<td style="text-align: right;">0.076</td>
<td style="text-align: right;">50.96</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3.731</td>
<td style="text-align: right;">4.030</td>
</tr>
<tr class="even">
<td style="text-align: left;">bty_avg</td>
<td style="text-align: right;">0.067</td>
<td style="text-align: right;">0.016</td>
<td style="text-align: right;">4.09</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.035</td>
<td style="text-align: right;">0.099</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>표 @ref(tab:regtable-11)의 결과인 회귀 표의 <code>estimate</code> 열에 있는 값들을 사용하여, 우리는 그림 @ref(fig:regline)에 있는 “최적적합” 회귀선의 방정식을 얻을 수 있습니다.</p>
<p><span class="math display">\[
\begin{aligned}
\widehat{y} &amp;= b_0 + b_1 \cdot x\\
\widehat{\text{score}} &amp;= b_0 + b_{\text{bty}\_\text{avg}} \cdot\text{bty}\_\text{avg}\\
&amp;= 3.880 + 0.067\cdot\text{bty}\_\text{avg}
\end{aligned}
\]</span></p>
<p>여기서 <span class="math inline">\(b_0\)</span>는 적합된 절편이고 <span class="math inline">\(b_1\)</span>은 <code>bty_avg</code>에 대한 적합된 기울기입니다. 적합된 기울기 값 <span class="math inline">\(b_1\)</span> = 0.067에 대한 해석을 상기해 보십시오.</p>
<blockquote class="blockquote">
<p>“외모” 평점이 1단위 증가할 때마다, 강의 평가 점수는 평균적으로 0.067단위씩 증가하는 경향이 있습니다.</p>
</blockquote>
<p>따라서 기울기 값은 <span class="math inline">\(y\)</span> 변수인 <code>score</code>와 <span class="math inline">\(x\)</span> 변수인 <code>bty_avg</code> 사이의 관계를 정량화합니다. 우리는 또한 <span class="math inline">\(b_0\)</span> = 3.88인 절편 값에 대해서도 논의했는데, 가능한 “외모” 점수의 범위가 0을 포함하지 않기 때문에 실질적인 해석의 여지는 없었습니다.</p>
</section>
<section id="표집-시나리오" class="level3" data-number="12.1.2">
<h3 data-number="12.1.2" class="anchored" data-anchor-id="표집-시나리오"><span class="header-section-number">12.1.2</span> 표집 시나리오</h3>
<p>이제 하위 섹션 @ref(terminology-and-notation)에서 공부했던 표집과 관련된 용어 및 표기법의 관점에서 이 연구를 다시 살펴보겠습니다.</p>
<p>먼저, 이 463개 강의의 강사들을 더 큰 <strong>연구 모집단(study population)</strong>에서 추출한 <strong>대표 표본(representative sample)</strong>으로 간주해 봅시다. 우리의 경우, 연구 모집단은 UT 오스틴의 <strong>모든</strong> 강사이며, 이 463개 강의를 가르친 강사들의 표본이 대표 표본이라고 가정하겠습니다. 안타깝게도 연구자들이 사용한 <strong>표집 방법론(sampling methodology)</strong>에 대해 더 자세히 알지 못한다면, 우리는 단지 이 두 가지 사실을 <em>가정</em>할 수 있을 뿐입니다.</p>
<p>우리는 이 <span class="math inline">\(n\)</span> = 463개의 강의를 하나의 표본으로 보고 있으므로, 우리가 구한 적합된 기울기 <span class="math inline">\(b_1\)</span> = 0.067을 <strong>모집단 기울기(population slope)</strong> <span class="math inline">\(\beta_1\)</span>의 <strong>점 추정치(point estimate)</strong>로 볼 수 있습니다. 즉, <span class="math inline">\(\beta_1\)</span>은 UT 오스틴의 <strong>모든</strong> 강사에 대해 강의 점수(<code>score</code>)와 외모 평점(<code>bty_avg</code>) 사이의 관계를 정량화합니다. 마찬가지로 적합된 절편 <span class="math inline">\(b_0\)</span> = 3.88을 UT 오스틴의 모든 강사에 대한 <strong>모집단 절편(population intercept)</strong> <span class="math inline">\(\beta_0\)</span>의 점 추정치로 볼 수 있습니다.</p>
<p>이 두 아이디어를 종합하면, 적합된 선의 방정식 <span class="math inline">\(\widehat{y}\)</span> = <span class="math inline">\(b_0 + b_1 \cdot x\)</span> = <span class="math inline">\(3.880 + 0.067 \cdot \text{bty}\_\text{avg}\)</span>를 실재하지만 알 수 없는 어떤 <strong>모집단 선(population line)</strong> <span class="math inline">\(y = \beta_0 + \beta_1 \cdot x\)</span>의 추정치로 볼 수 있습니다. 따라서 우리는 강의 평가 분석과 그동안 보았던 모든 표집 시나리오 사이의 공통점을 찾을 수 있습니다. 이 장에서는 표 @ref(tab:summarytable-ch11)에 표시된 회귀 기울기의 마지막 시나리오에 초점을 맞출 것입니다.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small">
<caption>추론을 위한 표집 시나리오들</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Scenario</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Population parameter</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Notation</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Point estimate</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Symbol(s)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right; width: 0.5in;">1</td>
<td style="text-align: left; width: 0.7in;">Population proportion</td>
<td style="text-align: left; width: 1in;">$p$</td>
<td style="text-align: left; width: 1.1in;">Sample proportion</td>
<td style="text-align: left; width: 1in;">$\widehat{p}$</td>
</tr>
<tr class="even">
<td style="text-align: right; width: 0.5in;">2</td>
<td style="text-align: left; width: 0.7in;">Population mean</td>
<td style="text-align: left; width: 1in;">$\mu$</td>
<td style="text-align: left; width: 1.1in;">Sample mean</td>
<td style="text-align: left; width: 1in;">$\overline{x}$ or $\widehat{\mu}$</td>
</tr>
<tr class="odd">
<td style="text-align: right; width: 0.5in;">3</td>
<td style="text-align: left; width: 0.7in;">Difference in population proportions</td>
<td style="text-align: left; width: 1in;">$p_1 - p_2$</td>
<td style="text-align: left; width: 1.1in;">Difference in sample proportions</td>
<td style="text-align: left; width: 1in;">$\widehat{p}_1 - \widehat{p}_2$</td>
</tr>
<tr class="even">
<td style="text-align: right; width: 0.5in;">4</td>
<td style="text-align: left; width: 0.7in;">Difference in population means</td>
<td style="text-align: left; width: 1in;">$\mu_1 - \mu_2$</td>
<td style="text-align: left; width: 1.1in;">Difference in sample means</td>
<td style="text-align: left; width: 1in;">$\overline{x}_1 - \overline{x}_2$ or $\widehat{\mu}_1 - \widehat{\mu}_2$</td>
</tr>
<tr class="odd">
<td style="text-align: right; width: 0.5in;">5</td>
<td style="text-align: left; width: 0.7in;">Population regression slope</td>
<td style="text-align: left; width: 1in;">$\beta_1$</td>
<td style="text-align: left; width: 1.1in;">Fitted regression slope</td>
<td style="text-align: left; width: 1in;">$b_1$ or $\widehat{\beta}_1$</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>이제 적합된 기울기 <span class="math inline">\(b_1\)</span>과 적합된 절편 <span class="math inline">\(b_0\)</span>를 <strong>표본</strong>에 기반한 <strong>점 추정치</strong>로 보고 있으므로, 이러한 추정치들 역시 <strong>표집 가변성(sampling variability)</strong>의 영향을 받게 됩니다. 다시 말해, 다른 <span class="math inline">\(n\)</span> = 463개 강의와 강사들에 대한 새로운 데이터를 수집한다면, 새로운 적합된 기울기 <span class="math inline">\(b_1\)</span>은 0.067과 다를 가능성이 높습니다. 새로운 적합된 절편 <span class="math inline">\(b_0\)</span>도 마찬가지일 것입니다. 그런데 이 추정치들이 얼마나 많이 <strong>변할까요(vary)</strong>? 이 정보는 표 @ref(tab:regtable-11)의 회귀 표에 있는 나머지 열들에 들어 있습니다. 챕터 @ref(sampling)의 표집, 챕터 @ref(confidence-intervals)의 신뢰 구간, 챕터 @ref(hypothesis-testing)의 가설 검정에 대한 지식이 이 나머지 열들을 해석하는 데 도움이 될 것입니다.</p>
</section>
</section>
<section id="regression-interp" class="level2" data-number="12.2">
<h2 data-number="12.2" class="anchored" data-anchor-id="regression-interp"><span class="header-section-number">12.2</span> 회귀 표 해석하기</h2>
<p>우리는 지금까지 표 @ref(tab:regtable-11)의 회귀 표에서 왼쪽의 두 열인 <code>term</code>과 <code>estimate</code>에만 집중했습니다. 이제 표 @ref(tab:score-model-part-deux)에서 나머지 열들인 <code>std_error</code>, <code>statistic</code>, <code>p_value</code>, <code>lower_ci</code>, <code>upper_ci</code>로 관심을 돌려보겠습니다.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small">
<caption>이전에 보았던 회귀 표</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std_error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p_value</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">lower_ci</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">upper_ci</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">intercept</td>
<td style="text-align: right;">3.880</td>
<td style="text-align: right;">0.076</td>
<td style="text-align: right;">50.96</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3.731</td>
<td style="text-align: right;">4.030</td>
</tr>
<tr class="even">
<td style="text-align: left;">bty_avg</td>
<td style="text-align: right;">0.067</td>
<td style="text-align: right;">0.016</td>
<td style="text-align: right;">4.09</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.035</td>
<td style="text-align: right;">0.099</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>적합된 절편 <span class="math inline">\(b_0\)</span>에 대한 실질적인 해석이 부족하다는 점을 고려하여, 이 섹션에서는 적합된 기울기 <span class="math inline">\(b_1\)</span>에 해당하는 표의 두 번째 행에만 집중하겠습니다. 먼저 <code>std_error</code>, <code>statistic</code>, <code>p_value</code>, <code>lower_ci</code>, <code>upper_ci</code> 열들을 해석해 보겠습니다. 그 후 다가올 하위 섹션 @ref(regression-table-computation)에서 R이 이러한 값들을 어떻게 계산하는지 논의할 것입니다.</p>
<section id="regression-se" class="level3" data-number="12.2.1">
<h3 data-number="12.2.1" class="anchored" data-anchor-id="regression-se"><span class="header-section-number">12.2.1</span> 표준 오차</h3>
<p>표 @ref(tab:regtable-11)에 있는 회귀 표의 세 번째 열인 <code>std_error</code>는 우리 추정치의 <strong>표준 오차(standard error)</strong>에 해당합니다. 하위 섹션 @ref(sampling-definitions)에서 보았던 <strong>표준 오차</strong> 의 정의를 상기해 봅시다.</p>
<blockquote class="blockquote">
<p><strong>표준 오차</strong>는 표본으로부터 계산된 모든 점 추정치의 표준 편차입니다.</p>
</blockquote>
<p>그렇다면 이것이 적합된 기울기 <span class="math inline">\(b_1\)</span> = 0.067의 관점에서는 무엇을 의미할까요? 이 값은 강의 점수와 외모 점수가 쌍으로 이루어진 <span class="math inline">\(n\)</span> = 463개의 <strong>특정한 표본</strong>으로부터 얻은 적합된 기울기의 단 하나의 가능한 값일 뿐입니다. 그러나 만약 우리가 강의 점수와 외모 점수가 쌍으로 이루어진 다른 <span class="math inline">\(n\)</span> = 463개의 표본을 수집한다면, 우리는 거의 확실히 다른 적합된 기울기 <span class="math inline">\(b_1\)</span>을 얻게 될 것입니다. 이는 <strong>표집 가변성</strong> 때문입니다.</p>
<p>우리가 가상으로 강의 점수와 외모 점수 쌍으로 이루어진 그러한 표본을 1000개 수집하여, 거기서 얻은 1000개의 적합된 기울기 <span class="math inline">\(b_1\)</span> 값을 계산하고 이를 히스토그램으로 시각화했다고 가정해 봅시다. 이것은 하위 섹션 @ref(sampling-definitions)에서 정의한 <span class="math inline">\(b_1\)</span>의 <strong>표집 분포(sampling distribution)</strong>를 시각화한 것이 될 것입니다. 또한 <span class="math inline">\(b_1\)</span>의 <strong>표집 분포</strong>의 표준 편차에 <strong>표준 오차</strong>라는 특별한 이름이 붙는다는 점을 다시 떠올려 보십시오.</p>
<p>그림 @ref(fig:comparing-sampling-distributions)에서 삽의 크기가 25, 50, 100일 때 표본 비율 <span class="math inline">\(\widehat{p}\)</span>에 대해 세 개의 표집 분포를 구축했던 것을 상기해 보십시오. 우리는 표본 크기가 커짐에 따라 표집 분포가 좁아지는 것으로부터 알 수 있듯이 표준 오차가 감소하는 것을 관찰했습니다.</p>
<p><span class="math inline">\(b_1\)</span>의 <strong>표준 오차</strong>도 마찬가지로 서로 다른 표본들 사이에서 적합된 기울기 <span class="math inline">\(b_1\)</span>의 변동이 얼마나 될 것으로 예상되는지를 정량화합니다. 따라서 우리의 경우, <code>bty_avg</code> 기울기 변수에서 약 0.016 단위의 변동을 예상할 수 있습니다. <code>estimate</code>와 <code>std_error</code> 값은 모든 강사와 관련된 알 수 없는 모집단 기울기 <span class="math inline">\(\beta_1\)</span>의 값을 <strong>추론(inferring)</strong>하는 데 핵심적인 역할을 한다는 점을 기억하십시오.</p>
<p>섹션 @ref(infer-regression)에서는 <code>infer</code> 패키지를 사용하여 시뮬레이션을 수행하고, 이 사례에서 <span class="math inline">\(b_1\)</span>에 대한 부트스트랩 분포를 구축할 것입니다. 하위 섹션 @ref(bootstrap-vs-sampling)에서 보았듯이, 부트스트랩 분포는 모양이 비슷하다는 점에서 표집 분포에 대한 <strong>근사치</strong>입니다. 모양이 비슷하기 때문에 <strong>표준 오차</strong>도 비슷합니다. 하지만 표집 분포와 달리 부트스트랩 분포는 <strong>단 하나의</strong> 표본으로부터 구축되며, 이는 실제 생활에서 이루어지는 방식과 더 일치합니다.</p>
</section>
<section id="regression-test-statistic" class="level3" data-number="12.2.2">
<h3 data-number="12.2.2" class="anchored" data-anchor-id="regression-test-statistic"><span class="header-section-number">12.2.2</span> 검정 통계량</h3>
<p>표 @ref(tab:regtable-11)의 회귀 표에서 네 번째 열인 <code>statistic</code>은 다음 <strong>가설 검정</strong>과 관련된 <strong>검정 통계량</strong>에 해당합니다.</p>
<p><span class="math display">\[
\begin{aligned}
H_0 &amp;: \beta_1 = 0\\
\text{대 } H_A&amp;: \beta_1 \neq 0
\end{aligned}
\]</span></p>
<p>섹션 @ref(understanding-ht)에서 소개한 가설 검정과 관련된 용어, 표기법, 정의를 상기해 봅시다.</p>
<blockquote class="blockquote">
<p><strong>가설 검정</strong>은 서로 경쟁하는 두 가설 사이의 검정으로 구성됩니다. (1) <strong>귀무 가설</strong> <span class="math inline">\(H_0\)</span> 대 (2) <strong>대립 가설</strong> <span class="math inline">\(H_A\)</span>입니다.</p>
<p><strong>검정 통계량</strong>은 가설 검정에 사용되는 점 추정치/표본 통계량 공식입니다.</p>
</blockquote>
<p>여기서 우리의 <strong>귀무 가설</strong> <span class="math inline">\(H_0\)</span>는 모집단 기울기 <span class="math inline">\(\beta_1\)</span>이 0이라고 가정합니다. 만약 모집단 기울기 <span class="math inline">\(\beta_1\)</span>이 정말로 0이라면, 이는 우리 모집단의 <strong>모든</strong> 강사에 대해 강의 점수와 외모 점수 사이에 <strong>어떠한 실제적인 관계도 없음</strong>을 말하는 것입니다. 즉, <span class="math inline">\(x\)</span> = “외모” 점수가 <span class="math inline">\(y\)</span> = “강의 점수”에 아무런 영향을 미치지 않는다는 뜻입니다. 반면에 <strong>대립 가설</strong> <span class="math inline">\(H_A\)</span>는 모집단 기울기 <span class="math inline">\(\beta_1\)</span>이 0이 아니라고 가정하며, 이는 양수일 수도 있고 음수일 수도 있음을 의미합니다. 이는 강의 점수와 외모 점수 사이에 양(+)의 관계나 음(-)의 관계가 있음을 시사합니다. 우리는 이러한 대립 가설을 <strong>양측(two-sided)</strong> 가설이라고 불렀던 것을 기억하십시오. 관례적으로 회귀 분석을 위한 모든 가설 검정은 양측 대립 가설을 가정합니다.</p>
<p>섹션 @ref(ht-activity)의 <code>promotions</code> 활동에서 우리가 <strong>가정</strong>했던 성차별이 없는 “가상 세계(hypothesized universe)”를 떠올려 보십시오. 마찬가지로 여기서 이 가설 검정을 수행할 때, 우리는 강의 점수와 외모 점수 사이에 아무런 관계가 없는 “가상 세계”를 가정할 것입니다. 즉, 귀무 가설 <span class="math inline">\(H_0: \beta_1 = 0\)</span>이 참이라고 가정할 것입니다.</p>
<p>하지만 회귀 표의 <code>statistic</code> 열은 조금 까다롭습니다. 그것은 우리가 가설 검정을 위해 이론 기반 방법을 사용했던 하위 섹션 @ref(theory-hypo)에서 보았던 <strong>이표본 t-통계량</strong>과 매우 유사한 <strong>표준화된 t-검정 통계량</strong>에 해당합니다. 이 두 경우 모두 <strong>귀무 분포</strong>는 수학적으로 <strong>t-분포</strong>임이 증명될 수 있습니다. 이러한 검정 통계량은 통계적 추론을 처음 접하는 분들이 공부하기에 까다로울 수 있으므로, 일단 건너뛰고 p-값의 해석으로 넘어가겠습니다. 궁금하신 분들을 위해 하위 섹션 @ref(theory-regression)에 이 표준화된 t-검정 통계량에 대한 논의를 포함해 두었습니다.</p>
</section>
<section id="p-값" class="level3" data-number="12.2.3">
<h3 data-number="12.2.3" class="anchored" data-anchor-id="p-값"><span class="header-section-number">12.2.3</span> p-값</h3>
<p>표 @ref(tab:regtable-11)의 회귀 표에서 다섯 번째 열인 <code>p_value</code>는 가설 검정 <span class="math inline">\(H_0: \beta_1 = 0\)</span> 대 <span class="math inline">\(H_A: \beta_1 \neq 0\)</span>에 대한 <strong>p-값</strong>에 해당합니다.</p>
<p>다시 한번 섹션 @ref(understanding-ht)에서 소개한 가설 검정 관련 용어, 표기법, 정의를 상기하며 p-값의 정의에 집중해 봅시다.</p>
<blockquote class="blockquote">
<p><strong>p-값</strong>은 <strong>귀무 가설 <span class="math inline">\(H_0\)</span>가 참이라고 가정할 때</strong>, 관찰된 검정 통계량만큼 극단적이거나 그보다 더 극단적인 검정 통계량을 얻을 확률입니다.</p>
</blockquote>
<p>직관적으로 p-값이란, 강의 점수와 외모 점수 사이에 아무런 관계가 없는 “가상 세계”에서 관찰된 적합된 기울기 <span class="math inline">\(b_1\)</span> = 0.067이 얼마나 “극단적인지”를 정량화하는 것으로 생각할 수 있습니다.</p>
<p>섹션 @ref(ht-interpretation)에서 설명한 가설 검정 절차를 따르면, 이 사례에서 p-값이 0이므로 유의 수준 <span class="math inline">\(\alpha\)</span>를 어떻게 선택하든 <span class="math inline">\(H_0\)</span>를 기각하고 <span class="math inline">\(H_A\)</span>를 채택하게 됩니다. 비통계적인 용어로는 다음과 같습니다. “우리는 강의 점수와 외모 점수 사이에 관계가 없다는 가설을 기각하고, 관계가 있다는 가설을 채택한다.” 즉, 증거는 양(+)의 유의미한 관계가 있음을 시사합니다.</p>
<p>하지만 더 정확하게 말하자면, p-값은 관찰된 검정 통계량 4.09이 적절한 <strong>귀무 분포</strong>와 비교했을 때 얼마나 극단적인지에 해당합니다. 섹션 @ref(infer-regression)에서는 <code>infer</code> 패키지를 사용하여 이 사례에 대한 귀무 분포를 구축하는 시뮬레이션을 수행할 것입니다.</p>
<p>한 가지 추가로 주의할 점은, 이 가설 검정의 결과는 하위 섹션 @ref(regression-conditions)에서 곧 소개할 “회귀 추론을 위한 몇 가지 조건”이 충족될 때만 유효하다는 것입니다.</p>
</section>
<section id="신뢰-구간" class="level3" data-number="12.2.4">
<h3 data-number="12.2.4" class="anchored" data-anchor-id="신뢰-구간"><span class="header-section-number">12.2.4</span> 신뢰 구간</h3>
<p>표 @ref(tab:regtable-11)의 회귀 표에서 가장 오른쪽에 있는 두 열(<code>lower_ci</code>와 <code>upper_ci</code>)은 모집단 기울기 <span class="math inline">\(\beta_1\)</span>에 대한 95% <strong>신뢰 구간</strong>의 끝점에 해당합니다. 섹션 @ref(ci-build-up)에서 보았던 “그물이 물고기라면 신뢰 구간은 모집단 매개변수”라는 비유를 상기해 보십시오. <span class="math inline">\(\beta_1\)</span>에 대해 도출된 (0.035, 0.099)이라는 95% 신뢰 구간은 강의 점수와 외모 점수 사이의 선형 관계에 대한 모집단 기울기 <span class="math inline">\(\beta_1\)</span>의 타당한 범위로 생각할 수 있습니다.</p>
<p>하위 섹션 @ref(shorthand)에서 소개한 신뢰 구간의 정밀한 해석과 요약된 해석 중, 이 신뢰 구간에 대한 통계적으로 정밀한 해석은 다음과 같습니다. “만약 우리가 이 표집 절차를 아주 많이 반복한다면, 우리는 결과로 얻은 신뢰 구간의 약 95%가 모집단 기울기 <span class="math inline">\(\beta_1\)</span>의 값을 포함할 것으로 예상한다.” 하지만 우리는 이를 요약된 해석을 사용하여 “우리는 실제 모집단 기울기 <span class="math inline">\(\beta_1\)</span>이 0.035과 0.099 사이에 있다고 95% ’확신’한다”라고 정리하겠습니다.</p>
<p>이 경우 <span class="math inline">\(\beta_1\)</span>에 대한 95% 신뢰 구간 <span class="math inline">\((0.035, \, 0.099)\)</span>이 아주 특별한 값인 <span class="math inline">\(\beta_1 = 0\)</span>을 포함하지 않는다는 점에 주목하십시오. 모집단 회귀 기울기 <span class="math inline">\(\beta_1\)</span>이 0이라는 것은 강의 점수와 외모 점수 사이에 아무런 관계가 <strong>없다</strong>는 것과 같다고 언급했음을 기억하십시오. <span class="math inline">\(\beta_1 = 0\)</span>이 우리의 타당한 <span class="math inline">\(\beta_1\)</span> 범위 내에 있지 않으므로, 우리는 실제로 강의 점수와 외모 점수 사이에 관계가 있으며 그 관계가 양(+)의 관계라고 믿게 됩니다. 따라서 이 경우 95% 신뢰 구간을 통한 모집단 기울기 <span class="math inline">\(\beta_1\)</span>에 대한 결론은 가설 검정의 결론과 일치합니다. 즉, 증거는 강의 점수와 외모 점수 사이에 의미 있는 관계가 있음을 시사합니다.</p>
<p>하지만 하위 섹션 @ref(ci-width)에서 보았듯이, <strong>신뢰 수준</strong>은 신뢰 구간의 너비를 결정하는 여러 요인 중 하나입니다. 예를 들어, 95% 대신 더 높은 99% 신뢰 수준을 사용했다고 가정해 봅시다. 그러면 <span class="math inline">\(\beta_1\)</span>에 대한 신뢰 구간이 더 넓어지며 이제 0을 포함하게 될 수도 있습니다. 여기서 기억해야 할 교훈은 신뢰 구간에 기반한 어떤 결론이든 사용된 신뢰 수준에 크게 좌우된다는 것입니다.</p>
<p><span class="math inline">\(\beta_1\)</span>에 대한 95% 신뢰 구간의 두 끝점을 계산하는 데 어떤 계산이 들어갔을까요?</p>
<p>하위 섹션 @ref(theory-ci)에서 <code>lower_ci</code>와 <code>upper_ci</code>에 대해 논의했던 표집 그릇 예시를 상기해 보십시오. 표본 비율 <span class="math inline">\(\widehat{p}\)</span>의 표집 분포와 부트스트랩 분포가 대략 정규 분포를 따랐기 때문에, 우리는 부록 @ref(appendix-normal-curve)에 있는 종 모양 분포에 대한 경험 법칙을 사용하여 다음 방정식을 통해 <span class="math inline">\(p\)</span>에 대한 95% 신뢰 구간을 만들 수 있었습니다.</p>
<p><span class="math display">\[\widehat{p} \pm \text{MoE}_{\widehat{p}} = \widehat{p} \pm 1.96 \cdot \text{SE}_{\widehat{p}} = \widehat{p} \pm 1.96 \cdot \sqrt{\frac{\widehat{p}(1-\widehat{p})}{n}}\]</span></p>
<p>우리는 이를 표집 분포 및/또는 부트스트랩 분포가 대략적으로 종 모양을 띠는 다른 점 추정치들로 일반화할 수 있습니다.</p>
<p><span class="math display">\[\text{점 추정치} \pm \text{오차 한계(MoE)} = \text{점 추정치} \pm 1.96 \cdot \text{표준 오차(SE)}\]</span></p>
<p>섹션 @ref(infer-regression)에서 적합된 기울기 <span class="math inline">\(b_1\)</span>의 표집/부트스트랩 분포 역시 실제로 종 모양임을 보여줄 것입니다. 따라서 우리는 다음 방정식을 사용하여 <span class="math inline">\(\beta_1\)</span>에 대한 95% 신뢰 구간을 구축할 수 있습니다.</p>
<p><span class="math display">\[b_1 \pm \text{MoE}_{b_1} = b_1 \pm 1.96 \cdot \text{SE}_{b_1}\]</span></p>
<p>표준 오차 <span class="math inline">\(\text{SE}_{b_1}\)</span>의 값은 얼마일까요? 그것은 표 @ref(tab:regtable-11)의 회귀 표 세 번째 열에 있는 0.016입니다. 따라서 다음과 같습니다.</p>
<p><span class="math display">\[
\begin{aligned}
b_1 \pm 1.96 \cdot \text{SE}_{b_1} &amp;= 0.067 \pm 1.96 \cdot 0.016 = 0.067 \pm 0.031\\
&amp;= (0.036, 0.098)
\end{aligned}
\]</span></p>
<p>이는 표 @ref(tab:regtable-11)의 마지막 두 열에 있는 <span class="math inline">\((0.035, 0.099)\)</span> 신뢰 구간과 매우 흡사합니다.</p>
<p>하지만 가설 검정과 마찬가지로, 이 신뢰 구간의 결과 역시 섹션 @ref(regression-conditions)에서 논의할 “회귀 추론을 위한 조건”이 충족될 때만 유효합니다.</p>
</section>
<section id="regression-table-computation" class="level3" data-number="12.2.5">
<h3 data-number="12.2.5" class="anchored" data-anchor-id="regression-table-computation"><span class="header-section-number">12.2.5</span> R은 이 표를 어떻게 계산할까요?</h3>
<p>우리는 표 @ref(tab:regtable-11)에서 표준 오차, 검정 통계량, p-값, 그리고 95% 신뢰 구간의 끝점 값을 얻기 위해 시뮬레이션을 수행하지 않았으므로, 이러한 값들이 어떻게 계산되었는지 궁금할 것입니다. R은 보이지 않는 곳에서 무엇을 했을까요? R은 우리가 신뢰 구간과 가설 검정을 다룬 챕터 @ref(confidence-intervals)와 @ref(hypothesis-testing)에서 <code>infer</code> 패키지를 사용해 했던 것처럼 시뮬레이션을 실행했을까요?</p>
<p>정답은 “아니오”입니다! 하위 섹션 @ref(theory-ci)에서 보았던 신뢰 구간 구축을 위한 이론 기반 방법과 하위 섹션 @ref(theory-hypo)에서 보았던 이론 기반 가설 검정과 마찬가지로, 회귀 추론을 위한 신뢰 구간을 구축하고 가설 검정을 수행할 수 있게 해주는 수학적 공식들이 존재합니다. 이러한 공식들은 컴퓨터가 존재하지 않던 시절에 도출되었으므로, 이 책에서 우리가 했던 광범위한 컴퓨터 시뮬레이션을 실행하는 것은 불가능했을 것입니다. 우리는 이러한 공식들을 하위 섹션 @ref(theory-regression)의 “회귀 분석을 위한 이론 기반 추론”에서 제시합니다.</p>
<p>섹션 @ref(infer-regression)에서는 <code>infer</code> 패키지를 사용하여 신뢰 구간을 구축하고 가설 검정을 수행하는 시뮬레이션 기반 접근 방식을 살펴볼 것입니다. 특히 적합된 기울기 <span class="math inline">\(b_1\)</span>의 부트스트랩 분포가 보기에 정말 종 모양임을 확인시켜 드릴 것입니다.</p>
</section>
</section>
<section id="regression-conditions" class="level2" data-number="12.3">
<h2 data-number="12.3" class="anchored" data-anchor-id="regression-conditions"><span class="header-section-number">12.3</span> 회귀 추론을 위한 조건</h2>
<p>하위 섹션 @ref(se-method)에서 우리는 부트스트랩 분포가 종 모양인 경우에만 신뢰 구간 구축을 위해 표준 오차 기반 방법을 사용할 수 있다고 언급했습니다. 마찬가지로, 섹션 @ref(regression-interp)에서 설명한 가설 검정과 신뢰 구간 결과가 유효한 의미를 갖기 위해 충족되어야 하는 몇 가지 조건이 있습니다. 이러한 조건들은 가정된 근간의 수학 및 확률 이론이 성립하기 위해 반드시 충족되어야 합니다.</p>
<p>회귀 추론을 위해서는 네 가지 조건을 충족해야 합니다. 다음 조건들의 첫 글자를 따서 <strong>LINE</strong>이라고 부릅니다. 이는 선형 회귀를 수행할 때마다 확인해야 할 사항들을 기억하는 데 도움이 됩니다. </p>
<ol type="1">
<li>변수 사이 관계의 <strong>선형성(Linearity)</strong></li>
<li>잔차의 <strong>독립성(Independence)</strong></li>
<li>잔차의 <strong>정규성(Normality)</strong></li>
<li>잔차 분산의 <strong>등분산성(Equality of variance)</strong></li>
</ol>
<p>조건 <strong>L</strong>, <strong>N</strong>, <strong>E</strong>는 <strong>잔차 분석(residual analysis)</strong>이라 불리는 과정을 통해 검증할 수 있습니다. 조건 <strong>I</strong>는 데이터가 어떻게 수집되었는지에 대한 이해를 통해서만 검증할 수 있습니다.</p>
<p>이 섹션에서는 잔차에 대해 복습하고, 네 가지 <strong>LINE</strong> 조건이 각각 성립하는지 확인한 다음, 그 시사점에 대해 논의할 것입니다.</p>
<section id="잔차-복습" class="level3" data-number="12.3.1">
<h3 data-number="12.3.1" class="anchored" data-anchor-id="잔차-복습"><span class="header-section-number">12.3.1</span> 잔차 복습</h3>
<p>하위 섹션 @ref(model1points)에서 정의한 잔차를 상기해 봅시다. 잔차는 <strong>관찰값(observed value)</strong>에서 <strong>적합값(fitted value)</strong>을 뺀 것으로, <span class="math inline">\(y - \widehat{y}\)</span>로 표시합니다. 잔차는 그림 @ref(fig:regline)의 회귀선 위에 있는 관찰값 <span class="math inline">\(y\)</span>와 적합값 <span class="math inline">\(\widehat{y}\)</span> 사이의 오차 또는 “적합도 부족(lack-of-fit)”으로 생각할 수 있습니다. 그림 @ref(fig:residual-example)에서는 463개의 잔차 중 하나를 화살표로 예시하고, 그에 해당하는 관찰값과 적합값을 각각 원과 사각형으로 표시했습니다.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="10-inference-for-regression_files/figure-html/residual-example-1.png" class="img-fluid figure-img"></p>
<figcaption>관찰값, 적합값, 잔차의 예시.</figcaption>
</figure>
</div>
</div>
</div>
<p>또한, 저장된 회귀 모델 <code>score_model</code>에 <code>get_regression_points()</code> 함수를 적용하여 <span class="math inline">\(n\)</span> = 463개의 모든 잔차 계산을 자동화할 수 있습니다. <code>residual</code> 열의 결과값들이 대략 <code>score - score_hat</code>과 일치하는지 확인해 보십시오(반올림 오차로 인해 약간의 차이가 있을 수 있습니다).</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 회귀 모델 적합:</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>score_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(score <span class="sc">~</span> bty_avg, <span class="at">data =</span> evals_ch5)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="co"># 회귀 지점 가져오기:</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>regression_points <span class="ot">&lt;-</span> <span class="fu">get_regression_points</span>(score_model)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>regression_points</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 463 × 5
      ID score bty_avg score_hat residual
   &lt;int&gt; &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
 1     1   4.7    5         4.21    0.486
 2     2   4.1    5         4.21   -0.114
 3     3   3.9    5         4.21   -0.314
 4     4   4.8    5         4.21    0.586
 5     5   4.6    3         4.08    0.52 
 6     6   4.3    3         4.08    0.22 
 7     7   2.8    3         4.08   -1.28 
 8     8   4.1    3.33      4.10   -0.002
 9     9   3.4    3.33      4.10   -0.702
10    10   4.5    3.17      4.09    0.409
# ℹ 453 more rows</code></pre>
</div>
</div>
<p><strong>잔차 분석</strong>은 조건 <strong>L</strong>, <strong>N</strong>, <strong>E</strong>를 검증하기 위해 사용되며, 적절한 데이터 시각화를 통해 수행할 수 있습니다. 더 정교한 통계적 접근 방식들도 존재하지만, 여기서는 플롯을 살펴보는 훨씬 간단한 방식에 집중하겠습니다.</p>
</section>
<section id="관계의-선형성" class="level3" data-number="12.3.2">
<h3 data-number="12.3.2" class="anchored" data-anchor-id="관계의-선형성"><span class="header-section-number">12.3.2</span> 관계의 선형성</h3>
<p>첫 번째 조건은 결과 변수 <span class="math inline">\(y\)</span>와 설명 변수 <span class="math inline">\(x\)</span> 사이의 관계가 <strong>선형(Linear)</strong>이어야 한다는 것입니다. 설명 변수 <span class="math inline">\(x\)</span>를 “외모” 점수로, 결과 변수 <span class="math inline">\(y\)</span>를 강의 점수로 설정했던 그림 @ref(fig:regline)의 산점도를 상기해 봅시다. 여러분은 <span class="math inline">\(x\)</span>와 <span class="math inline">\(y\)</span> 사이의 관계가 선형이라고 하시겠습니까? 선 주위에 점들이 흩어져 있기 때문에 말하기가 조금 어렵습니다. 저자들의 의견으로는, 이 관계는 “충분히 선형적”이라고 느껴집니다.</p>
<p>그림 @ref(fig:non-linear)에서는 <span class="math inline">\(x\)</span>와 <span class="math inline">\(y\)</span> 사이의 관계가 명확하게 선형이 아닌 예를 제시합니다. 이 경우 점들은 명확하게 직선을 형성하지 않고 오히려 U자형 다항식 곡선을 형성합니다. 이런 경우 회귀 분석을 통한 추론의 어떤 결과도 유효하지 않을 것입니다.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="10-inference-for-regression_files/figure-html/non-linear-1.png" class="img-fluid figure-img"></p>
<figcaption>명확하게 비선형인 관계의 예시.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="잔차의-독립성" class="level3" data-number="12.3.3">
<h3 data-number="12.3.3" class="anchored" data-anchor-id="잔차의-독립성"><span class="header-section-number">12.3.3</span> 잔차의 독립성</h3>
<p>두 번째 조건은 잔차들이 서로 <strong>독립(Independent)</strong>이어야 한다는 것입니다. 다시 말해, 우리 데이터의 서로 다른 관찰값들은 서로 독립적이어야 합니다.</p>
<p>우리 UT 오스틴 데이터의 경우, 463개 강의에 대한 데이터가 있지만, 이 463개 강의는 실제로는 94명의 서로 다른 강사들에 의해 진행되었습니다. 즉, 동일한 교수가 우리 데이터에 여러 번 포함되어 있는 경우가 많습니다. <code>evals_ch5</code> 데이터 프레임을 만드는 데 사용했던 원래의 <code>evals</code> 데이터 프레임에는 교수를 식별하기 위한 익명 아이디 변수인 <code>prof_ID</code>가 있습니다.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>evals <span class="sc">%&gt;%</span> </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(ID, prof_ID, score, bty_avg)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 463 × 4
      ID prof_ID score bty_avg
   &lt;int&gt;   &lt;int&gt; &lt;dbl&gt;   &lt;dbl&gt;
 1     1       1   4.7    5   
 2     2       1   4.1    5   
 3     3       1   3.9    5   
 4     4       1   4.8    5   
 5     5       2   4.6    3   
 6     6       2   4.3    3   
 7     7       2   2.8    3   
 8     8       3   4.1    3.33
 9     9       3   3.4    3.33
10    10       4   4.5    3.17
# ℹ 453 more rows</code></pre>
</div>
</div>
<p>예를 들어, <code>prof_ID</code>가 1인 교수는 데이터의 처음 4개 강의를 가르쳤고, <code>prof_ID</code>가 2인 교수는 그다음 3개 강의를 가르치는 식입니다. 동일한 교수가 이 처음 4개 강의를 가르쳤다는 점을 고려하면, 이 4개의 강의 점수가 서로 관련이 있다고 생각하는 것이 타당합니다. 만약 어떤 교수가 한 수업에서 높은 <code>score</code>를 받는다면, 다른 수업에서도 높은 <code>score</code>를 받을 가능성이 꽤 큽니다. 따라서 이 데이터 세트는 463개 강의를 463명의 고유한 교수들이 가르쳤을 때와는 다른 정보를 제공합니다.</p>
<p>이런 경우, 관찰값 사이에 <em>의존성(dependence)</em>이 존재한다고 말합니다. 교수 1이 가르친 처음 4개 강의는 서로 의존적이고, 교수 2가 가르친 그다음 3개 강의도 서로 관련이 있는 식입니다. 이 데이터를 적절하게 분석하려면 우리가 동일한 교수들에 대해 <em>반복 측정(repeated measures)</em>을 했다는 사실을 반드시 고려해야 합니다.</p>
<p>따라서 이 사례에서는 독립성 조건이 충족되지 않습니다. 이것이 우리의 분석에 무엇을 의미할까요? 나머지 두 조건을 확인한 후, 다가올 하위 섹션 @ref(what-is-the-conclusion)에서 이 문제를 다루겠습니다.</p>
</section>
<section id="잔차의-정규성" class="level3" data-number="12.3.4">
<h3 data-number="12.3.4" class="anchored" data-anchor-id="잔차의-정규성"><span class="header-section-number">12.3.4</span> 잔차의 정규성</h3>
<p>세 번째 조건은 잔차들이 <strong>정규(Normal)</strong> 분포를 따라야 한다는 것입니다. 또한, 이 분포의 중심은 0이어야 합니다. 즉, 때때로 회귀 모델은 양(+)의 오차(<span class="math inline">\(y - \widehat{y} &gt; 0\)</span>)를 낼 수 있고, 또 어떤 때는 그에 상응하는 음(-)의 오차(<span class="math inline">\(y - \widehat{y} &lt; 0\)</span>)를 낼 수 있습니다. 그러나 <em>평균적으로</em> 오차는 0이어야 하며, 그 모양은 종 모양과 비슷해야 합니다.</p>
<p>잔차의 정규성을 확인하는 가장 간단한 방법은 그림 @ref(fig:model1residualshist)에 시각화된 히스토그램을 살펴보는 것입니다.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(regression_points, <span class="fu">aes</span>(<span class="at">x =</span> residual)) <span class="sc">+</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="fl">0.25</span>, <span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"잔차"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="10-inference-for-regression_files/figure-html/model1residualshist-1.png" class="img-fluid figure-img"></p>
<figcaption>잔차의 히스토그램.</figcaption>
</figure>
</div>
</div>
</div>
<p>이 히스토그램은 음수 잔차보다 양수 잔차가 더 많음을 보여줍니다. <span class="math inline">\(y &gt; \widehat{y}\)</span>일 때 잔차 <span class="math inline">\(y-\widehat{y}\)</span>가 양수이므로, 우리 회귀 모델의 적합된 강의 점수 <span class="math inline">\(\widehat{y}\)</span>가 실제 강의 점수 <span class="math inline">\(y\)</span>를 <strong>과소평가(underestimate)</strong>하는 경향이 있는 것 같습니다. 또한, 이 히스토그램은 왼쪽에 꼬리가 있다는 점에서 약간의 <strong>왼쪽으로 치우침(left-skew)</strong>을 보입니다. 이는 잔차들이 <strong>음의 왜도(negative skew)</strong>를 나타낸다고 말하는 또 다른 방법입니다.</p>
<p>이것이 문제일까요? 다시 말씀드리자면, 대답에는 어느 정도의 주관성이 개입됩니다. 저자들의 생각으로는, 잔차의 왜도가 약간 있기는 하지만 급격하지는 않다고 느껴집니다. 반면에 다른 사람들은 우리의 판단에 동의하지 않을 수도 있습니다.</p>
<p>그림 @ref(fig:normal-residuals)에서는 잔차가 정규 분포를 명확하게 따르는 예와 그렇지 않은 예를 제시합니다. 오른쪽에 있는 명확하게 비정규적인 잔차를 낳는 모델의 경우, 회귀 분석을 통한 추론의 어떤 결과도 유효하지 않을 것입니다.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="10-inference-for-regression_files/figure-html/normal-residuals-1.png" class="img-fluid figure-img"></p>
<figcaption>명확하게 정규적인 잔차와 명확하게 비정규적인 잔차의 예시.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="등분산성" class="level3" data-number="12.3.5">
<h3 data-number="12.3.5" class="anchored" data-anchor-id="등분산성"><span class="header-section-number">12.3.5</span> 등분산성</h3>
<p>네 번째이자 마지막 조건은 잔차들이 설명 변수 <span class="math inline">\(x\)</span>의 모든 값에 대해 <strong>동일(Equal)</strong>한 분산을 가져야 한다는 것입니다. 다시 말해, 잔차의 값과 퍼짐 정도(spread)가 설명 변수 <span class="math inline">\(x\)</span>의 값에 의존해서는 안 됩니다.</p>
<p>그림 @ref(fig:regline)의 산점도를 상기해 보십시오. x축에는 설명 변수 <span class="math inline">\(x\)</span>인 “외모” 점수가, y축에는 결과 변수 <span class="math inline">\(y\)</span>인 강의 점수가 있었습니다. 대신, 그림 @ref(fig:numxplot6)에서 보는 것처럼 x축은 동일한 값을 유지하되 y축에 잔차 <span class="math inline">\(y-\widehat{y}\)</span>를 놓은 산점도를 만들어 보겠습니다.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(regression_points, <span class="fu">aes</span>(<span class="at">x =</span> bty_avg, <span class="at">y =</span> residual)) <span class="sc">+</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"외모 점수"</span>, <span class="at">y =</span> <span class="st">"잔차"</span>) <span class="sc">+</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">col =</span> <span class="st">"blue"</span>, <span class="at">size =</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="10-inference-for-regression_files/figure-html/numxplot6-1.png" class="img-fluid figure-img"></p>
<figcaption>외모 점수에 따른 잔차 플롯.</figcaption>
</figure>
</div>
</div>
</div>
<p>그림 @ref(fig:numxplot6)은 그림 @ref(fig:regline)의 회귀선이 포함된 플롯에서 회귀선을 <span class="math inline">\(y=0\)</span>으로 평평하게 펴놓은 수정된 버전이라고 생각할 수 있습니다. 이 플롯을 볼 때, <span class="math inline">\(y=0\)</span> 선 주위의 잔차들의 퍼짐 정도가 설명 변수 <span class="math inline">\(x\)</span>인 “외모” 점수의 모든 값에 대해 일정하다고 하시겠습니까? 이 질문은 다분히 정성적이고 주관적인 성격을 띠기 때문에 사람마다 다른 대답을 내놓을 수 있습니다. 예를 들어, 어떤 사람들은 <span class="math inline">\(x\)</span> 값이 작을 때가 클 때보다 잔차의 변동이 약간 더 크다고 말할 수 있습니다. 하지만 분산이 <em>급격하게</em> 일정하지 않은 것은 아니라고 주장할 수도 있습니다.</p>
<p>그림 @ref(fig:equal-variance-residuals)에서는 잔차의 분산이 설명 변수 <span class="math inline">\(x\)</span>의 모든 값에 대해 명확하게 동일하지 않은 예를 제시합니다.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="10-inference-for-regression_files/figure-html/equal-variance-residuals-1.png" class="img-fluid figure-img"></p>
<figcaption>명확하게 동일하지 않은 분산의 예시.</figcaption>
</figure>
</div>
</div>
</div>
<p><span class="math inline">\(x\)</span> 값이 커짐에 따라 잔차의 퍼짐 정도가 어떻게 증가하는지 관찰해 보십시오. 이러한 상황을 <strong>이분산성(heteroskedasticity)</strong>이라고 합니다. 잔차에서 이러한 패턴을 보이는 모델에 기반한 회귀 분석 추론의 결과는 유효하지 않을 것입니다.</p>
</section>
<section id="what-is-the-conclusion" class="level3" data-number="12.3.6">
<h3 data-number="12.3.6" class="anchored" data-anchor-id="what-is-the-conclusion"><span class="header-section-number">12.3.6</span> 결론이 무엇인가요?</h3>
<p>회귀 분석을 위한 네 가지 조건을 다시 나열하고, 우리 분석에서 이 조건들이 충족되었는지 표시해 보겠습니다.</p>
<ol type="1">
<li>변수 사이 관계의 <strong>선형성(Linearity)</strong>: 예</li>
<li>잔차의 <strong>독립성(Independence)</strong>: 아니요</li>
<li>잔차의 <strong>정규성(Normality)</strong>: 어느 정도</li>
<li>잔차 분산의 <strong>등분산성(Equality of variance)</strong>: 예</li>
</ol>
<p>그렇다면 이것이 섹션 @ref(regression-interp)에서 얻은 신뢰 구간과 가설 검정 결과에 어떤 의미가 있을까요?</p>
<p>첫째, <strong>독립성(Independence)</strong> 조건입니다. <code>evals_ch5</code> 데이터의 서로 다른 행들 사이에 의존성이 존재한다는 사실은 반드시 해결되어야 합니다. 더 발전된 통계학 과정에서는 이러한 의존성을 회귀 모델에 어떻게 통합하는지 배우게 될 것입니다. 그러한 기술 중 하나가 <strong>계층형/다층 모델링(hierarchical/multilevel modeling)</strong>입니다.</p>
<p>둘째, 조건 <strong>L</strong>, <strong>N</strong>, <strong>E</strong>가 충족되지 않을 때는 종종 우리 모델에 결함이 있음을 의미합니다. 예를 들어, 우리가 “외모” 점수에서 했던 것처럼 단일 설명 변수만 사용하는 것이 불충분할 수 있습니다. 챕터 @ref(multiple-regression)에서 했던 것처럼 다중 회귀 모델에 더 많은 설명 변수를 포함하거나, 하나 이상의 변수를 변환하거나, 아예 다른 모델링 기술을 사용해야 할 수도 있습니다. 이러한 결함을 해결하는 방법에 대해 더 알고 싶다면, 더 발전된 회귀 모델링 방법에 대한 수업을 듣거나 관련 서적을 찾아보아야 합니다.</p>
<p>우리 사례에서 우리가 할 수 있는 최선은 신뢰 구간과 가설 검정이 제시하는 결과를 “예비적인(preliminary)” 것으로 보는 것입니다. 예비 분석은 강의 점수와 외모 점수 사이에 유의미한 관계가 있음을 시사하지만, 특히 네 가지 조건이 충족되도록 예비 모델 <code>score ~ bty_avg</code>를 개선하는 등의 추가 조사가 필요합니다. 네 가지 조건이 대략적으로 충족될 때, 우리는 신뢰 구간과 p-값에 더 큰 확신을 가질 수 있습니다.</p>
<p>회귀 문제에서 추론을 위한 조건은 신뢰 구간 구축과 가설 검정 수행 과정에서 매우 중요한 회귀 분석의 핵심 부분입니다. 하지만 실제 세상의 회귀 분석에서는 모든 조건이 완벽하게 충족되지 않는 경우가 많습니다. 또한 보셨다시피, <strong>L</strong>, <strong>N</strong>, <strong>E</strong> 조건을 확인하기 위한 잔차 분석에는 어느 정도 주관성이 개입됩니다. 그렇다면 무엇을 할 수 있을까요? 저자로서 우리는 모든 결과를 전달할 때 투명성을 가질 것을 권장합니다. 이를 통해 분석의 이해관계자들은 모델의 결함이나 모델이 “충분히 좋은지” 여부를 알 수 있습니다. 가정을 확인하는 과정이 다소 모호한 “상황에 따라 다르다”는 결과로 이어지기도 했지만, 저자들은 여러분이 앞으로 마주하게 될 어려운 통계적 결정을 내리는 데 도움을 주기 위해 이러한 시나리오들을 보여주기로 결정했습니다.</p>
<div class="cell" data-layout-align="center" type="learncheck">
<div class="learncheck">
<p>
<strong><em>학습 확인</em></strong>
</p>
</div>
</div>
<p><strong>(LC10.1)</strong> <code>age</code>(나이)를 설명 변수로, 강의 <code>score</code>(점수)를 결과 변수로 사용하는 회귀 분석을 계속 진행해 봅시다.</p>
<ul>
<li><code>get_regression_points()</code> 함수를 사용하여 463명의 모든 강사에 대한 관찰값, 적합값, 잔차를 구하십시오.</li>
<li>잔차 분석을 수행하고 잔차에서 어떠한 체계적인 패턴이 있는지 찾아보십시오. 이상적으로는 패턴이 거의 없거나 아예 없어야 하지만, 여기서 발견한 내용에 대해 의견을 제시해 보십시오.</li>
</ul>
<div class="cell" data-layout-align="center" type="learncheck">
<div class="learncheck">

</div>
</div>
</section>
</section>
<section id="infer-regression" class="level2" data-number="12.4">
<h2 data-number="12.4" class="anchored" data-anchor-id="infer-regression"><span class="header-section-number">12.4</span> 시뮬레이션 기반 회귀 분석 추론</h2>
<p>하위 섹션 @ref(regression-table-computation)에서 회귀 표의 세 번째부터 일곱 번째 열을 해석할 때, R은 이러한 값을 계산하기 위해 시뮬레이션을 수행하지 않는다고 언급했습니다. 대신 R은 수학 공식을 포함하는 이론 기반 방법을 사용합니다.</p>
<p>이 섹션에서는 이전에 챕터 @ref(confidence-intervals)와 @ref(hypothesis-testing)에서 배운 시뮬레이션 기반 방법을 사용하여 표 @ref(tab:regtable-11)의 회귀 표에 있는 값들을 재현해 보겠습니다. 구체적으로 다음과 같이 <code>infer</code> 패키지 워크플로를 사용할 것입니다.</p>
<ul>
<li>복원 추출 부트스트랩을 사용하여 모집단 기울기 <span class="math inline">\(\beta_1\)</span>에 대한 95% 신뢰 구간을 구축합니다. 우리는 이전에 <code>pennies</code> 데이터를 사용한 섹션 @ref(bootstrap-process)와 <code>mythbusters_yawn</code> 데이터를 사용한 섹션 @ref(case-study-two-prop-ci)에서 이 작업을 수행했습니다.</li>
<li>순열 검정(permutation test)을 사용하여 <span class="math inline">\(H_0: \beta_1 = 0\)</span> 대 <span class="math inline">\(H_A: \beta_1 \neq 0\)</span>의 가설 검정을 수행합니다. 우리는 이전에 <code>promotions</code> 데이터를 사용한 섹션 @ref(ht-infer)와 <code>movies_sample</code> IMDb 데이터를 사용한 섹션 @ref(ht-case-study)에서 이 작업을 수행했습니다.</li>
</ul>
<section id="기울기에-대한-신뢰-구간" class="level3" data-number="12.4.1">
<h3 data-number="12.4.1" class="anchored" data-anchor-id="기울기에-대한-신뢰-구간"><span class="header-section-number">12.4.1</span> 기울기에 대한 신뢰 구간</h3>
<p>하위 섹션 @ref(infer-workflow)에서 설명한 <code>infer</code> 워크플로를 사용하여 <span class="math inline">\(\beta_1\)</span>에 대한 95% 신뢰 구간을 구축해 보겠습니다. 구체적으로, 먼저 463개 강의로 구성된 우리의 단일 표본을 사용하여 적합된 기울기 <span class="math inline">\(b_1\)</span>에 대한 부트스트랩 분포를 구축할 것입니다.</p>
<ol type="1">
<li><code>score ~ bty_avg</code> 공식을 사용하여 <code>evals_ch5</code>에서 관심 있는 변수들을 <code>specify()</code> 합니다.</li>
<li>원래 463개 강의 표본에서 복원 추출을 통한 <code>bootstrap</code> 리샘플링을 사용하여 복제본을 <code>generate()</code> 합니다. <code>type = "bootstrap"</code>을 사용하여 <code>reps = 1000</code>개의 복제본을 생성합니다.</li>
<li>관심 있는 요약 통계량인 적합된 <code>slope</code> <span class="math inline">\(b_1\)</span>을 <code>calculate()</code> 합니다.</li>
</ol>
<p>이 부트스트랩 분포를 사용하여 백분위수 방법과 (적절한 경우) 표준 오차 방법으로 95% 신뢰 구간을 구축할 것입니다. 이 사례에서 복원 추출 부트스트랩은 <strong>행 단위(row-by-row)</strong>로 수행된다는 점에 유의하는 것이 중요합니다. 따라서 <code>score</code>와 <code>bty_avg</code> 값의 원래 쌍은 항상 함께 유지되지만, 서로 다른 쌍들이 여러 번 리샘플링될 수 있습니다. 결과로 얻은 신뢰 구간은 UT 오스틴의 <strong>모든</strong> 교수에 대해 강의 점수와 “외모” 점수 사이의 관계를 정량화하는 알 수 없는 모집단 기울기 <span class="math inline">\(\beta_1\)</span>의 타당한 값의 범위를 나타낼 것입니다.</p>
<p>먼저 적합된 기울기 <span class="math inline">\(b_1\)</span>에 대한 부트스트랩 분포를 구축해 보겠습니다.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>bootstrap_distn_slope <span class="ot">&lt;-</span> evals_ch5 <span class="sc">%&gt;%</span> </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">specify</span>(<span class="at">formula =</span> score <span class="sc">~</span> bty_avg) <span class="sc">%&gt;%</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">generate</span>(<span class="at">reps =</span> <span class="dv">1000</span>, <span class="at">type =</span> <span class="st">"bootstrap"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">calculate</span>(<span class="at">stat =</span> <span class="st">"slope"</span>)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>bootstrap_distn_slope</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,000 × 2
   replicate   stat
       &lt;int&gt;  &lt;dbl&gt;
 1         1 0.0651
 2         2 0.0382
 3         3 0.108 
 4         4 0.0667
 5         5 0.0716
 6         6 0.0855
 7         7 0.0625
 8         8 0.0413
 9         9 0.0796
10        10 0.0761
# ℹ 990 more rows</code></pre>
</div>
</div>
<p><code>stat</code> 열에 1000개의 부트스트랩된 기울기 <span class="math inline">\(b_1\)</span> 값이 있는 것을 확인해 보십시오. 그림 @ref(fig:bootstrap-distribution-slope)에서 1000개의 부트스트랩된 값들을 시각화해 보겠습니다.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">visualize</span>(bootstrap_distn_slope)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="10-inference-for-regression_files/figure-html/bootstrap-distribution-slope-1.png" class="img-fluid figure-img"></p>
<figcaption>기울기의 부트스트랩 분포.</figcaption>
</figure>
</div>
</div>
</div>
<p>부트스트랩 분포가 대략 종 모양인 것을 확인해 보십시오. 하위 섹션 @ref(bootstrap-vs-sampling)에서 보았듯이, <span class="math inline">\(b_1\)</span>의 부트스트랩 분포의 모양은 <span class="math inline">\(b_1\)</span>의 표집 분포 모양과 매우 비슷합니다.</p>
<section id="백분위수-방법" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="백분위수-방법">백분위수 방법</h4>
<p>먼저, 백분위수 방법을 사용하여 <span class="math inline">\(\beta_1\)</span>에 대한 95% 신뢰 구간을 계산해 보겠습니다. 중앙의 95% 값을 포함하는 2.5% 백분위수와 97.5% 백분위수를 찾아낼 것입니다. 이 방법은 부트스트랩 분포가 반드시 정규 분포를 따를 필요는 없다는 점을 상기하십시오.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>percentile_ci <span class="ot">&lt;-</span> bootstrap_distn_slope <span class="sc">%&gt;%</span> </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">get_confidence_interval</span>(<span class="at">type =</span> <span class="st">"percentile"</span>, <span class="at">level =</span> <span class="fl">0.95</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>percentile_ci</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  lower_ci upper_ci
     &lt;dbl&gt;    &lt;dbl&gt;
1   0.0323   0.0990</code></pre>
</div>
</div>
<p>이에 따라 도출된 <span class="math inline">\(\beta_1\)</span>에 대한 백분위수 기반 95% 신뢰 구간 (0.032, 0.099)은 회귀 표 @ref(tab:regtable-11)에 있는 신뢰 구간 (0.035, 0.099)과 유사합니다.</p>
</section>
<section id="표준-오차-방법" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="표준-오차-방법">표준 오차 방법</h4>
<p>그림 @ref(fig:bootstrap-distribution-slope)의 부트스트랩 분포가 대략 종 모양으로 보이므로, 표준 오차 방법을 사용하여 <span class="math inline">\(\beta_1\)</span>에 대한 95% 신뢰 구간을 구축할 수도 있습니다.</p>
<p>이를 위해 먼저 표준 오차 기반 신뢰 구간의 중심 역할을 할 적합된 기울기 <span class="math inline">\(b_1\)</span>을 계산해야 합니다. 회귀 표 @ref(tab:regtable-11)에서 이것이 <span class="math inline">\(b_1\)</span> = 0.067임을 확인했지만, <code>generate()</code> 단계를 제외한 <code>infer</code> 파이프라인을 사용하여 계산할 수도 있습니다.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>observed_slope <span class="ot">&lt;-</span> evals <span class="sc">%&gt;%</span> </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">specify</span>(score <span class="sc">~</span> bty_avg) <span class="sc">%&gt;%</span> </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">calculate</span>(<span class="at">stat =</span> <span class="st">"slope"</span>)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>observed_slope</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Response: score (numeric)
Explanatory: bty_avg (numeric)
# A tibble: 1 × 1
    stat
   &lt;dbl&gt;
1 0.0666</code></pre>
</div>
</div>
<p>그런 다음 <code>level = 0.95</code>인 <code>get_ci()</code> 함수를 사용하여 <span class="math inline">\(\beta_1\)</span>에 대한 95% 신뢰 구간을 계산합니다. <code>point_estimate</code> 인자를 <code>observed_slope</code>인 0.067로 설정하여 신뢰 구간의 중심을 정한다는 점에 유의하십시오.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>se_ci <span class="ot">&lt;-</span> bootstrap_distn_slope <span class="sc">%&gt;%</span> </span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">get_ci</span>(<span class="at">level =</span> <span class="fl">0.95</span>, <span class="at">type =</span> <span class="st">"se"</span>, <span class="at">point_estimate =</span> observed_slope)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>se_ci</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  lower_ci upper_ci
     &lt;dbl&gt;    &lt;dbl&gt;
1   0.0334   0.0999</code></pre>
</div>
</div>
<p>이에 따라 도출된 <span class="math inline">\(\beta_1\)</span>에 대한 표준 오차 기반 95% 신뢰 구간 <span class="math inline">\((0.033, 0.1)\)</span>은 회귀 표 @ref(tab:regtable-11)의 신뢰 구간 <span class="math inline">\((0.035, 0.099)\)</span>과 약간 다릅니다.</p>
</section>
<section id="세-가지-방법-비교" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="세-가지-방법-비교">세 가지 방법 비교</h4>
<p>그림 @ref(fig:bootstrap-distribution-slope-CI)에서 세 가지 신뢰 구간을 비교해 보겠습니다. 백분위수 기반 신뢰 구간은 실선으로, 표준 오차 기반 신뢰 구간은 파란색 점선으로, 그리고 표 @ref(tab:regtable-11)의 회귀 표에서 얻은 이론 기반 신뢰 구간 (0.035, 0.099)은 검은색 점선(dotted)으로 표시되어 있습니다.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">visualize</span>(bootstrap_distn_slope) <span class="sc">+</span> </span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">shade_confidence_interval</span>(<span class="at">endpoints =</span> percentile_ci, <span class="at">fill =</span> <span class="cn">NULL</span>, </span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>                            <span class="at">linetype =</span> <span class="st">"solid"</span>, <span class="at">color =</span> <span class="st">"grey90"</span>) <span class="sc">+</span> </span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">shade_confidence_interval</span>(<span class="at">endpoints =</span> se_ci, <span class="at">fill =</span> <span class="cn">NULL</span>, </span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>                            <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"grey60"</span>) <span class="sc">+</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">shade_confidence_interval</span>(<span class="at">endpoints =</span> <span class="fu">c</span>(<span class="fl">0.035</span>, <span class="fl">0.099</span>), <span class="at">fill =</span> <span class="cn">NULL</span>, </span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>                            <span class="at">linetype =</span> <span class="st">"dotted"</span>, <span class="at">color =</span> <span class="st">"black"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="10-inference-for-regression_files/figure-html/bootstrap-distribution-slope-CI-1.png" class="img-fluid figure-img"></p>
<figcaption>기울기에 대한 세 가지 신뢰 구간 비교.</figcaption>
</figure>
</div>
</div>
</div>
<p>세 구간 모두 매우 유사하다는 것을 알 수 있습니다! 또한, <span class="math inline">\(\beta_1\)</span>에 대한 세 신뢰 구간 중 어느 것도 0을 포함하지 않으며 모두 0보다 큰 곳에 위치합니다. 이는 실제 강의 점수와 “외모” 점수 사이에 유의미한 양(+)의 관계가 있음을 시사합니다.</p>
</section>
</section>
<section id="기울기에-대한-가설-검정" class="level3" data-number="12.4.2">
<h3 data-number="12.4.2" class="anchored" data-anchor-id="기울기에-대한-가설-검정"><span class="header-section-number">12.4.2</span> 기울기에 대한 가설 검정</h3>
<p>이제 <span class="math inline">\(H_0: \beta_1 = 0\)</span> 대 <span class="math inline">\(H_A: \beta_1 \neq 0\)</span>의 가설 검정을 수행해 보겠습니다. 그림 @ref(fig:htdowney)의 “오직 하나의 검정만 존재한다” 다이어그램에 있는 가설 검정 패러다임을 따르는 <code>infer</code> 패키지를 사용할 것입니다.</p>
<p>먼저 귀무 가설 <span class="math inline">\(H_0\)</span>에서 가정한 것처럼 <span class="math inline">\(\beta_1\)</span>이 0이라는 것이 무엇을 의미하는지 생각해 봅시다. <span class="math inline">\(\beta_1 = 0\)</span>이면 강의 점수와 “외모” 점수 사이에 아무런 관계가 없음을 의미한다고 언급했습니다. 따라서 이 특정한 귀무 가설 <span class="math inline">\(H_0\)</span>를 가정한다는 것은 우리의 “가설된 우주”에서는 <code>score</code>와 <code>bty_avg</code> 사이에 아무런 관계가 없음을 의미합니다. 따라서 우리는 아무런 문제 없이 <code>bty_avg</code> 변수를 무작위로 섞거나(shuffle) 순열(permute)을 수행할 수 있습니다.</p>
<p>우리는 다음과 같은 단계들을 수행하여 적합된 기울기 <span class="math inline">\(b_1\)</span>의 귀무 분포를 구축합니다. 용어, 표기법 및 정의와 관련된 섹션 @ref(understanding-ht)에서 <strong>귀무 분포(null distribution)</strong>를 귀무 가설 <span class="math inline">\(H_0\)</span>가 참이라고 가정했을 때 우리 검정 통계량 <span class="math inline">\(b_1\)</span>의 표집 분포로 정의했음을 상기하십시오.</p>
<ol type="1">
<li><code>score ~ bty_avg</code> 공식을 사용하여 <code>evals_ch5</code>에서 관심 있는 변수들을 <code>specify()</code> 합니다.</li>
<li><code>independence</code>라는 귀무 가설을 <code>hypothesize()</code> 합니다. 섹션 @ref(ht-infer)에서 보았듯이, 이는 가설 검정을 위해 추가되어야 하는 단계입니다.</li>
<li>원래 463개 강의 표본에서 값들을 순열/섞기를 수행하여 복제본을 <code>generate()</code> 합니다. 여기서 <code>type = "permute"</code>를 사용하여 <code>reps = 1000</code>개의 복제본을 생성합니다.</li>
<li>관심 있는 검정 통계량인 적합된 <code>slope</code> <span class="math inline">\(b_1\)</span>을 <code>calculate()</code> 합니다.</li>
</ol>
<p>이 경우, 우리는 1000번 동안 <code>score</code> 값들에 대해 <code>bty_avg</code> 값들의 순열을 수행합니다. 두 변수 사이에 아무런 관계가 없다는 “가설된 우주”를 가정했으므로 이러한 섞기/순열을 수행할 수 있습니다. 그런 다음 <code>generate</code>된 1000개의 표본 각각에 대해 <code>"slope"</code> 계수를 <code>calculate</code> 합니다.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>null_distn_slope <span class="ot">&lt;-</span> evals <span class="sc">%&gt;%</span> </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">specify</span>(score <span class="sc">~</span> bty_avg) <span class="sc">%&gt;%</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">hypothesize</span>(<span class="at">null =</span> <span class="st">"independence"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">generate</span>(<span class="at">reps =</span> <span class="dv">1000</span>, <span class="at">type =</span> <span class="st">"permute"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">calculate</span>(<span class="at">stat =</span> <span class="st">"slope"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>그림 @ref(fig:null-distribution-slope)에서 적합된 기울기 <span class="math inline">\(b_1\)</span>에 대한 귀무 분포 결과를 확인해 보십시오.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="10-inference-for-regression_files/figure-html/null-distribution-slope-1.png" class="img-fluid figure-img"></p>
<figcaption>기울기의 귀무 분포.</figcaption>
</figure>
</div>
</div>
</div>
<p>이 분포가 <span class="math inline">\(b_1 = 0\)</span>을 중심으로 하고 있음에 주목하십시오. 이는 우리의 가설된 우주에서 <code>score</code>와 <code>bty_avg</code> 사이에 아무런 관계가 없으므로 <span class="math inline">\(\beta_1 = 0\)</span>이라고 가정했기 때문입니다. 따라서 시뮬레이션을 통해 관찰되는 가장 전형적인 적합된 기울기 <span class="math inline">\(b_1\)</span>은 0입니다. 또한 이 중심값 0을 중심으로 변동이 있음을 확인해 보십시오.</p>
<p>그림 @ref(fig:p-value-slope)에서 관찰된 검정 통계량 <span class="math inline">\(b_1\)</span> = 0.067과 비교하여 귀무 분포의 p-값을 시각화해 보겠습니다. 이전의 <code>visualize()</code> 코드에 <code>shade_p_value()</code> 레이어를 추가하여 이를 수행할 것입니다.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="10-inference-for-regression_files/figure-html/p-value-slope-1.png" class="img-fluid figure-img"></p>
<figcaption>귀무 분포와 p-값.</figcaption>
</figure>
</div>
</div>
</div>
<p>관찰된 적합 기울기 0.067이 이 귀무 분포의 오른쪽 끝에서 훨씬 멀리 떨어져 있고 색칠된 영역이 겹치지 않으므로, p-값은 0이 될 것입니다. 하지만 완결성을 위해 <code>get_p_value()</code> 함수를 사용하여 p-값의 수치를 계산해 보겠습니다. 이 함수는 <code>shade_p_value()</code> 함수와 동일한 입력을 받는다는 점을 상기하십시오.</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>null_distn_slope <span class="sc">%&gt;%</span> </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">get_p_value</span>(<span class="at">obs_stat =</span> observed_slope, <span class="at">direction =</span> <span class="st">"both"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  p_value
    &lt;dbl&gt;
1       0</code></pre>
</div>
</div>
<p>이는 표 @ref(tab:regtable-11)의 회귀 표에 있는 p-값 0과 일치합니다. 따라서 우리는 대립 가설 <span class="math inline">\(H_A: \beta_1 \neq 0\)</span>을 지지하며 귀무 가설 <span class="math inline">\(H_0: \beta_1 = 0\)</span>을 기각합니다. 즉, UT 오스틴의 <strong>모든</strong> 강사에 대해 강의 점수와 “외모” 점수 사이에 유의미한 관계가 있음을 시사하는 증거가 있습니다.</p>
<p>회귀 분석의 추론 조건이 충족되고 귀무 분포가 종 모양인 경우, 방금 보여드린 시뮬레이션 기반 결과와 표 @ref(tab:regtable-11)의 회귀 표에 표시된 이론 기반 결과 사이에 유사한 결과를 얻을 가능성이 높습니다.</p>
<div class="cell" data-layout-align="center" type="learncheck">
<div class="learncheck">
<p>
<strong><em>학습 확인</em></strong>
</p>
</div>
</div>
<p><strong>(LC10.2)</strong> 이번에는 기울기 대신 상관 계수(correlation coefficient)에 대해 추론을 반복해 보십시오. <code>infer</code> 패키지의 <code>calculate()</code> 함수에서 <code>stat = "correlation"</code>을 구현하는 점에 유의하십시오.</p>
<div class="cell" data-layout-align="center" type="learncheck">
<div class="learncheck">

</div>
</div>
</section>
</section>
<section id="inference-conclusion" class="level2" data-number="12.5">
<h2 data-number="12.5" class="anchored" data-anchor-id="inference-conclusion"><span class="header-section-number">12.5</span> 결론</h2>
<!--
v2 TODO: Consider adding

### Relating regression to other methods

To conclude this chapter, we'll be investigating how regression relates to two different statistical techniques. One of them was covered already in this book, the difference in sample means, and the other is new to the text but is related, ANOVA. We'll see how both can be represented in the regression framework. The hope is that this closing section helps you to tie together many of the concepts you've seen in the Data Modeling and Statistical Inference parts of this book.

#### Two sample difference in means

#### ANOVA


-->
<section id="theory-regression" class="level3" data-number="12.5.1">
<h3 data-number="12.5.1" class="anchored" data-anchor-id="theory-regression"><span class="header-section-number">12.5.1</span> 회귀에 대한 이론 기반 추론</h3>
<p>하위 섹션 @ref(regression-table-computation)에서 표 @ref(tab:regtable-11)의 회귀 표를 해석할 때, R은 우리가 <code>infer</code> 패키지를 사용하여 챕터 @ref(confidence-intervals)와 @ref(hypothesis-testing)에서 했던 것처럼 신뢰 구간을 구축하고 가설 검정을 수행하기 위해 시뮬레이션 기반 방법을 사용하지 않는다고 언급했습니다. 대신 R은 하위 섹션 @ref(theory-ci)에서 본 이론 기반 신뢰 구간과 하위 섹션 @ref(theory-hypo)에서 본 이론 기반 가설 검정과 매우 유사하게 수학 공식을 사용하는 이론 기반 접근 방식을 사용합니다. 이러한 공식들은 컴퓨터가 존재하지 않던 시절에 유도되었으므로 대규모 시뮬레이션을 실행하는 것은 매우 노동 집약적인 일이었을 것입니다.</p>
<p>특히, 하위 섹션 @ref(theory-se)에서 본 표본 비율 <span class="math inline">\(\widehat{p}\)</span>의 표준 오차 공식과 하위 섹션 @ref(theory-hypo)에서 본 표본 평균의 차이 <span class="math inline">\(\overline{x}_1 - \overline{x}_2\)</span>의 표준 오차 공식과 마찬가지로, 적합된 기울기 <span class="math inline">\(b_1\)</span>의 표준 오차를 구하는 공식이 있습니다.</p>
<p><span class="math display">\[\text{SE}_{b_1} = \dfrac{\dfrac{s_y}{s_x} \cdot \sqrt{1-r^2}}{\sqrt{n-2}}\]</span></p>
<p>이 공식에는 많은 것이 담겨 있으므로, 먼저 각 기호가 무엇을 나타내는지 분석해 보겠습니다. 먼저 <span class="math inline">\(s_x\)</span>와 <span class="math inline">\(s_y\)</span>는 각각 설명 변수 <code>bty_avg</code>와 결과 변수 <code>score</code>의 <strong>표본 표준 편차</strong>입니다. 둘째, <span class="math inline">\(r\)</span>은 <code>score</code>와 <code>bty_avg</code> 사이의 표본 <strong>상관 계수</strong>입니다. 이는 챕터 @ref(regression)에서 0.187로 계산되었습니다. 마지막으로, <span class="math inline">\(n\)</span>은 <code>evals_ch5</code> 데이터 프레임에 있는 점들의 쌍의 수로, 여기서는 463입니다.</p>
<p>이 공식을 말로 풀어서 설명하면, <span class="math inline">\(b_1\)</span>의 표준 오차는 <span class="math inline">\(s_y / s_x\)</span> 항에서 측정된 결과 변수의 변동성과 설명 변수의 변동성 사이의 관계에 달려 있습니다. 다음으로, <span class="math inline">\(\sqrt{1-r^2}\)</span> 항에서 두 변수가 서로 어떻게 관련되어 있는지를 살펴봅니다.</p>
<p>하지만 앞의 공식에서 주목해야 할 가장 중요한 사실은 분모에 <span class="math inline">\(n - 2\)</span>가 있다는 것입니다. 즉, 표본 크기 <span class="math inline">\(n\)</span>이 증가할수록 표준 오차 <span class="math inline">\(\text{SE}_{b_1}\)</span>은 감소합니다. 하위 섹션 @ref(moral-of-the-story)에서 <span class="math inline">\(n\)</span> = 25, 50, 100개의 구멍이 있는 삽을 사용하여 시연했듯이, 적합된 기울기 <span class="math inline">\(b_1\)</span>의 표집 변동량은 표본 크기 <span class="math inline">\(n\)</span>에 따라 달라질 것입니다. 특히 표본 크기가 증가함에 따라 표집 분포와 부트스트랩 분포가 좁아지고 표준 오차 <span class="math inline">\(\text{SE}_{b_1}\)</span>이 감소합니다. 따라서 실제 모집단 기울기 <span class="math inline">\(\beta_1\)</span>에 대한 <span class="math inline">\(b_1\)</span>의 추정치는 점점 더 <strong>정밀(precise)</strong>해집니다.</p>
<p>R은 회귀 표의 세 번째 열에서 <span class="math inline">\(b_1\)</span>의 표준 오차를 구하기 위해 이 공식을 사용하며, 이어서 95% 신뢰 구간을 구축하는 데에도 사용합니다. 그렇다면 가설 검정은 어떨까요? 하위 섹션 @ref(theory-hypo)의 이론 기반 가설 검정에서와 마찬가지로 R은 가설 검정을 위한 검정 통계량으로 다음과 같은 <strong><span class="math inline">\(t\)</span>-통계량</strong>을 사용합니다.</p>
<p><span class="math display">\[
t = \dfrac{ b_1 - \beta_1}{ \text{SE}_{b_1}}
\]</span></p>
<p>가설 검정 중에는 귀무 가설 <span class="math inline">\(H_0: \beta_1 = 0\)</span>이 가정되므로 <span class="math inline">\(t\)</span>-통계량은 다음과 같이 됩니다.</p>
<p><span class="math display">\[
t = \dfrac{ b_1 - 0}{ \text{SE}_{b_1}} = \dfrac{ b_1 }{ \text{SE}_{b_1}}
\]</span></p>
<p><span class="math inline">\(b_1\)</span>과 <span class="math inline">\(\text{SE}_{b_1}\)</span>의 값은 무엇일까요? 이들은 표 @ref(tab:regtable-11) 회귀 표의 <code>estimate</code>와 <code>std_error</code> 열에 있습니다. 따라서 표에 있는 4.09 값은 0.067/0.016 = 4.188로 계산됩니다. 여기에는 반올림 오차로 인해 약간의 차이가 있음에 유의하십시오.</p>
<p>마지막으로, p-값을 계산하려면 관찰된 검정 통계량 4.09을 적절한 귀무 분포와 비교해야 합니다. 섹션 @ref(understanding-ht)에서 귀무 분포는 <strong>귀무 가설 <span class="math inline">\(H_0\)</span>가 참이라고 가정했을 때</strong> 검정 통계량의 표집 분포임을 상기하십시오. 하위 섹션 @ref(theory-hypo)의 이론 기반 가설 검정에서와 마찬가지로, 이 분포는 자유도가 <span class="math inline">\(df = n - 2 = 463 - 2 = 461\)</span>인 <span class="math inline">\(t\)</span>-분포임을 수학적으로 증명할 수 있습니다.</p>
<p>이 시점에서 약간 압도당하는 느낌이 들더라도 걱정하지 마십시오. 이론 기반 방법의 방정식을 완전히 이해하기 위해서는 이해해야 할 배경 이론이 많습니다. 하지만 신뢰 구간을 구축하고 가설 검정을 수행할 때 이론 기반 방법과 시뮬레이션 기반 방법은 종종 일관된 결과를 산출합니다. 앞서 언급했듯이, 저희의 의견으로는 이론 기반 방법보다 시뮬레이션 기반 방법이 갖는 두 가지 큰 장점은 (1) 통계적 추론을 처음 배우는 사람들이 이해하기 더 쉽고, (2) 이론 기반 방법과 수학 공식이 존재하지 않는 상황에서도 작동한다는 것입니다.</p>
</section>
<section id="통계적-추론-요약" class="level3" data-number="12.5.2">
<h3 data-number="12.5.2" class="anchored" data-anchor-id="통계적-추론-요약"><span class="header-section-number">12.5.2</span> 통계적 추론 요약</h3>
<p>하위 섹션 @ref(sampling-conclusion-table)의 “추론을 위한 표집 시나리오” 표에서 마지막 두 시나리오를 마쳤으며, 이를 표 @ref(tab:table-ch11)에 다시 표시했습니다.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small">
<caption>\label{tab:summarytable-ch9}추론을 위한 표집 시나리오</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Scenario</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Population parameter</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Notation</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Point estimate</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Symbol(s)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right; width: 0.5in;">1</td>
<td style="text-align: left; width: 1.5in;">Population proportion</td>
<td style="text-align: left; width: 0.65in;">$p$</td>
<td style="text-align: left; width: 1.6in;">Sample proportion</td>
<td style="text-align: left; width: 0.65in;">$\widehat{p}$</td>
</tr>
<tr class="even">
<td style="text-align: right; width: 0.5in;">2</td>
<td style="text-align: left; width: 1.5in;">Population mean</td>
<td style="text-align: left; width: 0.65in;">$\mu$</td>
<td style="text-align: left; width: 1.6in;">Sample mean</td>
<td style="text-align: left; width: 0.65in;">$\overline{x}$ or $\widehat{\mu}$</td>
</tr>
<tr class="odd">
<td style="text-align: right; width: 0.5in;">3</td>
<td style="text-align: left; width: 1.5in;">Difference in population proportions</td>
<td style="text-align: left; width: 0.65in;">$p_1 - p_2$</td>
<td style="text-align: left; width: 1.6in;">Difference in sample proportions</td>
<td style="text-align: left; width: 0.65in;">$\widehat{p}_1 - \widehat{p}_2$</td>
</tr>
<tr class="even">
<td style="text-align: right; width: 0.5in;">4</td>
<td style="text-align: left; width: 1.5in;">Difference in population means</td>
<td style="text-align: left; width: 0.65in;">$\mu_1 - \mu_2$</td>
<td style="text-align: left; width: 1.6in;">Difference in sample means</td>
<td style="text-align: left; width: 0.65in;">$\overline{x}_1 - \overline{x}_2$ or $\widehat{\mu}_1 - \widehat{\mu}_2$</td>
</tr>
<tr class="odd">
<td style="text-align: right; width: 0.5in;">5</td>
<td style="text-align: left; width: 1.5in;">Population regression slope</td>
<td style="text-align: left; width: 0.65in;">$\beta_1$</td>
<td style="text-align: left; width: 1.6in;">Fitted regression slope</td>
<td style="text-align: left; width: 0.65in;">$b_1$ or $\widehat{\beta}_1$</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>챕터 @ref(regression)와 @ref(multiple-regression)에서 배운 회귀 모델링 기술, 챕터 @ref(sampling)에서의 추론을 위한 표집에 대한 이해, 그리고 챕터 @ref(confidence-intervals)와 @ref(hypothesis-testing)의 신뢰 구간 및 가설 검정과 같은 통계적 추론 도구들을 갖춘 여러분은 이제 광범위한 데이터에서 변수 사이의 관계의 유의성을 연구할 준비가 되었습니다! 여기서 제시된 많은 아이디어는 다중 회귀 및 기타 더 발전된 모델링 기술로 확장될 수 있습니다.</p>
</section>
<section id="추가-자료" class="level3" data-number="12.5.3">
<h3 data-number="12.5.3" class="anchored" data-anchor-id="추가-자료"><span class="header-section-number">12.5.3</span> 추가 자료</h3>
<div class="cell" data-layout-align="center">
<p>이 장에서 사용된 모든 R 코드의 R 스크립트 파일은 <a href="scripts/10-inference-for-regression.R">여기</a>에서 이용 가능합니다.</p>
</div>
</section>
<section id="앞으로의-내용" class="level3" data-number="12.5.4">
<h3 data-number="12.5.4" class="anchored" data-anchor-id="앞으로의-내용"><span class="header-section-number">12.5.4</span> 앞으로의 내용</h3>
<p>이제 이 책의 마지막 주요 부분인 “<code>infer</code>를 이용한 통계적 추론”을 마쳤습니다. 마지막 챕터인 @ref(thinking-with-data)는 미국 워싱턴주 시애틀의 주택 가격과 같은 실제 데이터를 포함한 다양한 짧은 사례 연구들로 이 책을 마무리합니다. 이 책의 원칙들이 여러분이 데이터를 통해 훌륭한 스토리텔러가 되는 데 어떻게 도움이 되는지 확인하게 될 것입니다!</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./09-hypothesis-testing.html" class="pagination-link" aria-label="가설 검정">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">가설 검정</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./11-tell-your-story-with-data.html" class="pagination-link" aria-label="(PART) 결론">
        <span class="nav-page-text">(PART) 결론</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>