[workspace]
authors = ["deepthought <deepthough@postech.ac.kr>"]
channels = ["conda-forge"]
name = "ModernDive_book"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
render = "quarto render mybook"
preview = "quarto preview mybook"
setup-r = { cmd = "RScript -e 'if (!require(\"remotes\")) install.packages(\"remotes\", repos=\"https://cran.rstudio.com\"); if (!require(\"pak\")) install.packages(\"pak\", repos=\"https://cran.rstudio.com\"); pak::pkg_install(c(\"moderndive\", \"infer\", \"nycflights13\", \"fivethirtyeight\", \"gapminder\", \"ggplot2movies\", \"dygraphs\", \"ISLR\", \"janitor\", \"skimr\", \"broom\", \"ggrepel\", \"here\", \"kableExtra\", \"mvtnorm\", \"patchwork\", \"sessioninfo\", \"viridis\", \"webshot\", \"scales\"))'" }

[dependencies]
quarto = ">=1.8.27"
r-base = ">=4.4.2"
r-tidyverse = ">=2.0.0"
r-rmarkdown = "*"
r-knitr = "*"
r-bookdown = "*"
r-devtools = "*"
r-remotes = "*"
r-tinytex = "*"
r-bslib = "*"
r-fontawesome = "*"
r-downlit = "*"
r-xml2 = "*"
r-desc = "*"
"r-formula.tools" = "*"
r-profvis = "*"
r-dtplyr = "*"
r-dbplyr = "*"
r-gargle = "*"
r-httr2 = "*"
r-googledrive = "*"
r-googlesheets4 = "*"
r-modelr = "*"
r-reprex = "*"
r-rvest = "*"
r-conflicted = "*"
r-cpp11 = "*"
r-diffobj = "*"
r-farver = "*"
r-gert = "*"
r-gh = "*"
r-gitcreds = "*"
r-ini = "*"
r-rappdirs = "*"
r-rematch = "*"
r-zip = "*"
r-isoband = "*"
r-labeling = "*"
r-munsell = "*"
r-rcolorbrewer = "*"
r-viridislite = "*"
r-cachem = "*"
r-memoise = "*"
