```{r, include=FALSE}
source("_common.R")
```

# 사용된 R 패키지 버전 {#appendixE}

```{r message=FALSE, echo=FALSE, purl=FALSE}
# 내부적으로 필요하지만 본문에서는 필요하지 않은 패키지들입니다.
library(sessioninfo)
library(kableExtra)
```

만약 책에 있는 결과와 다른 결과를 보고 계신다면, 저희가 사용한 패키지의 정확한 버전을 설치하는 것을 권장합니다. 먼저 `install.packages("remotes")`를 통해 `remotes` 패키지를 설치한 후, `install_version()` 함수를 사용하세요. `package` 인수에는 패키지 이름을 따옴표 안에 넣고, `version` 인수에는 설치할 특정 버전 번호를 입력하면 됩니다.

```{r eval=FALSE}
remotes::install_version(package = "skimr", version = "1.0.6")
```

<!--
\begin{multicols}{2}
\setbox\ltmcbox\vbox{
\makeatletter\col@number\@ne
-->

```{r colophon, echo=FALSE}
package_info(needed_pkgs) %>% 
  as_tibble() %>% 
  filter(attached == TRUE | package %in% c("bookdown", "skimr")) %>% 
  select(package, version = ondiskversion) %>% 
  kable(
    booktabs = TRUE, 
    linesep = "",
    longtable = TRUE
  ) %>% 
  kable_styling(font_size = ifelse(knitr::is_latex_output(), 9, 16))
```

\vspace{-2in}
<!--
% Wrap this after the table to get into multiple columns
\unskip
\unpenalty
\unpenalty}
\unvbox\ltmcbox

\end{multicols}
-->

