project:
  type: book
  output-dir: _book
  resources:
    - data/
    - images/
    - rds/
    - previous_versions/
    - labs.html
    - regression-plane.html
    - bib/
    - style.css
    - purl.R

book:
  title: "ModernDive: 데이터 과학을 통한 통계적 추론"
  subtitle: "R과 Tidyverse에 대한 ModernDive 소개"
  author: "Chester Ismay and Albert Y. Kim"
  date: "2026-03-05"
  chapters:
    - index.qmd
    - 01-getting-started.qmd
    - part: "데이터 과학"
      chapters:
        - 02-visualization.qmd
        - 03-wrangling.qmd
        - 04-tidy.qmd
    - part: "데이터 모델링"
      chapters:
        - 05-regression.qmd
        - 06-multiple-regression.qmd
    - part: "통계적 추론"
      chapters:
        - 07-sampling.qmd
        - 08-confidence-intervals.qmd
        - 09-hypothesis-testing.qmd
    - part: "데이터 모델링(심화)"
      chapters:
        - 10-inference-for-regression.qmd
    - 11-tell-your-story-with-data.qmd
    - part: "부록"
      chapters:
        - 91-appendixA.qmd
        - 92-appendixB.qmd
        - 93-appendixC.qmd
        - 94-appendixD.qmd
        - 95-appendixE.qmd
        - NEWS.md
        - 99-references.qmd

bibliography: 
  - bib/books.bib
  - bib/packages.bib
  - bib/articles.bib
  - references.bib

format:
  html:
    theme:
      - cosmo
    number-sections: false